= Änderungen an Inhalten

Der Leitfaden bietet die Möglichkeit an, Änderungen an Inhalten über vordefinierte Elemente auszuzeichnen.
Er unterstützt die Auszeichnung von Inhalten in Erstellung, in Überarbeitung und in Deprecation.

IMPORTANT: Nachdem eine Änderung abgeschlossen ist, muss die Auszeichnung an allen betreffenden Stellen entfernt werden.


[[erstellung]]
== Inhalte in Erstellung

Wenn Inhalte neu erstellt werden, geschieht dies meist über einen längeren Zeitraum hinweg.
Während der Erstellung sind diese neuen Inhalte in der Regel noch nicht in der ganzen IsyFact berücksichtigt.

Um solche Inhalte auszuzeichnen, bietet der Leitfaden eine allgemeine Variante, eine für Seiten und eine für Bausteine an.
Es sollte immer die Variante gewählt werden, die am besten zum Wirkungsbereich (_Scope_) der Änderung passt.

=== Allgemeiner Hinweis

Dieser Hinweis kann an beliebigen Stellen im Text platziert werden.
Es empfiehlt sich, ihn direkt nach einer Überschrift zu platzieren.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-new.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-new.adoc[]

=== Hinweis für Seiten

Dieser Hinweis sollte als erster Inhalt auf einer Seite stehen.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-new-page.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-new-page.adoc[]

=== Hinweis für Bausteine

Dieser Hinweis sollte auf allen Seiten des Bausteins platziert werden.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-new-building-block.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-new-building-block.adoc[]

=== Kurzhinweis

Der Kurzhinweis kann in Tabellen, für Verweise oder ähnliche Textstellen verwendet werden.

*Markup:*

[source,asciidoc]
....
icon:puzzle-piece[title="In Erstellung"] (Inhalt in Erstellung)
....

*Beispiel (Verweis):*

<<erstellung,icon:puzzle-piece[title="In Erstellung"] (Inhalt in Erstellung)>>


[[ueberarbeitung]]
== Inhalte in Überarbeitung

Von Zeit zu Zeit werden Inhalte aus diversen Gründen grundlegend überarbeitet.
Während der Überarbeitung sind diese Inhalte möglicherweise inkonsistent, sowohl in sich als auch zum Rest der IsyFact.

Um solche Inhalte auszuzeichnen, bietet der Leitfaden eine allgemeine Variante, eine für Seiten und eine für Bausteine an.
Es sollte immer die Variante gewählt werden, die am besten zum Wirkungsbereich (_Scope_) der Änderung passt.

=== Allgemeiner Hinweis

Dieser Hinweis kann an beliebigen Stellen im Text platziert werden.
Es empfiehlt sich, ihn direkt nach einer Überschrift zu platzieren.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-revised.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-revised.adoc[]

=== Hinweis für Seiten

Dieser Hinweis sollte als erster Inhalt auf einer Seite stehen.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-revised-page.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-revised-page.adoc[]

=== Hinweis für Bausteine

Dieser Hinweis sollte auf allen Seiten des Bausteins platziert werden.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-revised-building-block.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-revised-building-block.adoc[]

=== Kurzhinweis

Der Kurzhinweis kann in Tabellen, für Verweise oder ähnliche Textstellen verwendet werden.

*Markup:*

[source,asciidoc]
....
icon:wrench[title="In Überarbeitung"] (Inhalt in Überarbeitung)
....

*Beispiel:*

<<ueberarbeitung,icon:wrench[title="In Überarbeitung"] (Inhalt in Überarbeitung)>>


[[deprecation]]
== Veraltete Inhalte

Gelegentlich veralten Inhalte, werden aber erst zu einem späteren Zeitpunkt aus der Dokumentation entfernt.

Um solche Inhalte auszuzeichnen, bietet der Leitfaden eine allgemeine Variante, eine für Seiten und eine für Bausteine an.
Es sollte immer die Variante gewählt werden, die am besten zum Wirkungsbereich (_Scope_) der Änderung passt.

=== Allgemeiner Hinweis

Dieser Hinweis kann an beliebigen Stellen im Text platziert werden.
Es empfiehlt sich, ihn direkt nach einer Überschrift zu platzieren.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-deprecated.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-deprecated.adoc[]

=== Hinweis für Seiten

Dieser Hinweis sollte als erster Inhalt auf einer Seite stehen.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-deprecated-page.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-deprecated-page.adoc[]

=== Hinweis für Bausteine

Dieser Hinweis sollte auf allen Seiten des Bausteins platziert werden.

*Markup:*

[source,asciidoc]
....
\include::documentation-guide::partial$content-deprecated-building-block.adoc[]
....

*Ergebnis:*

include::documentation-guide::partial$content-deprecated-building-block.adoc[]

[[deprecation-kurzhinweis]]
=== Kurzhinweis

Der Kurzhinweis kann in Tabellen, für Verweise oder ähnliche Textstellen verwendet werden.

*Markup:*

[source,asciidoc]
....
🚫 [.line-through]#(Veralteter Inhalt)#
....

*Beispiel:*

<<deprecation,🚫 [.line-through]#(Veralteter Inhalt)#>>

[[deprecation-verweis-neue-inhalte]]
=== Verweis auf stattdessen gültige Inhalte

Auszeichnungen für veraltete Inhalte, bis auf den <<deprecation-kurzhinweis>>, können optional einen Verweis auf stattdessen gültige Inhalte beinhalten.
Dies ist dann sinnvoll, wenn Teile der Dokumentation durch andere ersetzt werden, zum Beispiel bei einem Produktwechsel oder der Ablösung eines Bausteins durch einen anderen.

*Markup:*

[source,asciidoc]
....
:linkaktuell: xref:<Verweis zur neuen Seite>.adoc[diese Inhalte]
\include::documentation-guide::partial$content-deprecated-building-block.adoc[]
....

*Ergebnis:*

:linkaktuell: xref:documentation-guide::guides/content-changes.adoc[diese Inhalte]
include::documentation-guide::partial$content-deprecated-building-block.adoc[]

[[deprecation-antora-component-version]]
=== Auszeichnung veralteter Antora-Komponenten

Die Auszeichnung für veraltete Inhalte kann optional auch auf Ebene der Antora-Komponente erfolgen.
Dafür wird sie in der xref:create-antora-component.adoc#antora-komponente-konfiguration-aufbau[Konfigurationsdatei der Komponente] entsprechend gekennzeichnet.

.Auszeichnung für einen veralteten Baustein (`antora.yml`)
[source,yaml]
....
title: Baustein XYZ 🚫
....

IMPORTANT: Sind mehrere Versionen der Antora-Komponente veröffentlicht, muss die Anpassung in jeder Version geschehen!