= Veröffentlichung von Inhalten

Die Online-Dokumentation besteht im Wesentlichen aus veröffentlichten Antora-Komponenten.
Dieser Guide beschreibt, wie Antora-Komponenten in die Online-Dokumentation <<antora-komponente-aufnehmen,*aufgenommen*>> und aus ihr <<antora-komponente-entfernen,*entfernt*>> werden.

NOTE: Für diesen Guide ist ein grundlegendes Verständnis des https://docs.antora.org/antora/latest/playbook/[Playbooks] sowie von https://docs.github.com/de/actions[GitHub Actions] nützlich.

[[antora-komponente-aufnehmen]]
== Aufnahme einer Antora-Komponente

Die Repositories der IsyFact verwenden Git LFS.
Durch die fehlende Unterstützung von Git LFS seitens Antora muss nicht nur das Playbook, sondern auch der CI-Build, angepasst werden.

[[anpassung-ci-build]]
=== Anpassung des CI-Builds

Um den fehlenden LFS-Support von Antora zu kompensieren, checkt der CI-Build das Repository mithilfe der https://github.com/actions/checkout[Checkout-Action] manuell aus.
Die Checkout-Action unterstützt Git LFS.

NOTE: Die Nutzung der Checkout-Action ist in der README des Repositories dokumentiert.
Besonders empfehlenswert ist die https://github.com/actions/checkout?tab=readme-ov-file#usage[Übersicht aller Parameter] sowie die https://github.com/actions/checkout?tab=readme-ov-file#scenarios[Liste gängiger Beispiele].

Zur Veröffentlichung einer Antora-Komponente muss dem https://github.com/IsyFact/isyfact.github.io/blob/main/.github/workflows/antora_build.yml[Workflow des CI-Builds] eine neue Checkout-Action hinzugefügt werden.

.Konfiguration der Checkout-Action für die IsyFact-Standards (Release 3.x)
[source,yaml]
----
jobs:
  Build:
    steps:
      - name: Checkout isyfact-standards (release/3.x)
        uses: actions/checkout@v4
        with:
          repository: IsyFact/isyfact-standards
          ref: release/3.x
          lfs: true
          sparse-checkout: isyfact-standards-doc/src/docs/antora
          path: isyfact-standards-3.x
----

TIP: Die Nutzung von `sparse-checkout` wird empfohlen, um nur die Dateien auszuchecken, die für den Build der Dokumentation benötigt werden.

[[anpassung-playbook]]
=== Anpassung des Playbooks

Dem https://github.com/IsyFact/isyfact.github.io/blob/main/antora-playbook.yml[Playbook] muss für das ausgecheckte Repository eine neue _Content Source_ hinzugefügt werden.

[[content-source-branches]]
==== Content Source auf Basis von Branches

.Konfiguration einer Content Source auf Basis eines Branches
[source,yaml]
----
content:
  sources:
    - url: ./isyfact-standards-3.x
      branches: release/3.x
      start_path: isyfact-standards-doc/src/docs/antora
      version:
        'release/(*)': $1
        'master': '{next}.x' <.>
        '(*)': $1
----
<.> `\{next}` bezeichnet hierbei die nächste Hauptversion.

Hierbei muss:

* die `url` aus dem Playbook auf den `path` aus der Checkout-Action zeigen,
* der `start_path` aus dem Playbook im `sparse_checkout` aus der Checkout-Action enthalten sein,
* der Parameter `branches` auf den ausgecheckten Git-Branch gesetzt sein, um den lokalen, ausgecheckten Stand zu verwenden,
* der Parameter `version` das Mapping der Git-Referenzen auf Versionen festlegen.

NOTE: Beinhaltet eine Content Source mehrere Antora-Komponenten, so ist der Parameter
https://docs.antora.org/antora/latest/playbook/content-source-start-paths/#start-paths-key[_start_paths_] zu verwenden.

[[content-source-tags]]
==== Content Source auf Basis von Tags

.Konfiguration einer Content Source auf Basis eines Tags
[source,yaml]
----
content:
  sources:
    - url: ./isyfact-standards-4.0.0
      branches: HEAD
      start_path: isyfact-standards-doc/src/docs/antora
      version: '{tag}'
----

Hierbei muss aufgrund des Git LFS Workarounds:

* der Parameter `branches` auf `HEAD` zeigen,
* der Parameter `version` gleich dem Tag sein.

Ansonsten sind die gleichen Punkte wie bei <<content-source-branches>> zu beachten.

WARNING: Antora rät generell davon ab, Dokumentation https://docs.antora.org/antora/latest/playbook/content-tags/[aus Tags heraus] zu veröffentlichen.

[[playbook-lokale-entwicklung]]
=== Playbook für lokale Entwicklung
Für die lokale Entwicklung ist es sinnvoll, ein https://github.com/IsyFact/isyfact.github.io/blob/main/antora-playbook-local.yml["lokales" Playbook] zu pflegen.
Das lokale Playbook unterscheidet sich in folgenden Punkten vom zentralen Playbook:

* eine Content Source beinhaltet mehrere Git Branches oder Tags,
* es werden _Feature_ Branches für eine Vorschau der Beiträge unterstützt,
* die Pflege der Branches erfolgt unter Umständen lokal.

.Konfiguration einer Content Source im lokalen Playbook
[source,yaml]
----
content:
  sources:
    - url: ../isyfact-standards
      branches: [HEAD, master, release/4.x, release/3.x]
      tags: [3.2.1, 4.0.0]
      start_path: isyfact-standards-doc/src/docs/antora
      version:
        'feature/(*)': $1
        'release/(*)': $1
        'master': '{next}.x' <.>
        '(*)': $1
----
<.> `\{next}` bezeichnet hierbei die nächste Hauptversion.

Hierbei muss:

* die `url` aus dem Playbook auf den lokalen Checkout-Pfad zeigen,
* der `start_path` auf die Antora-Komponenten-Konfiguration (antora.yml) verweisen,
* der Parameter `branches` bzw. `tags` die für die Veröffentlichung bestimmten Git-Referenzen beinhalten,
* der Parameter `version` das Mapping der Git-Referenzen auf Versionen festlegen.


[[antora-komponente-entfernen]]
== Entfernung einer Antora-Komponente

Prinzipiell müssen zur Entfernung einer Antora-Komponente aus der Online-Dokumentation die Anpassungen aus <<antora-komponente-aufnehmen>> rückgängig gemacht werden.

Zusätzlich ist darauf zu achten, dass durch die Entfernung einer Antora-Komponente keine ungültigen Verweise entstehen.
Hierzu geben die https://github.com/IsyFact/isyfact.github.io/actions/workflows/antora_build.yml[Logs der CI-Builds] (oder lokalen Builds) Aufschluss.
Werden dort noch Verweise auf die entfernte Antora-Komponente als ungültig gemeldet, müssen die entsprechenden Stellen in der Dokumentation angepasst werden.