variables:
  MAVEN_OPTS: "-Xmx2048M -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end"

image: $BUILDIMAGE_LEGACY

stages:
  - documentation

cache:
  paths:
   - aptcache/
   - .m2/repository
  key: "isyfactdoc"

.template: &vorlage
  stage: documentation
  tags:
   - docker
   - zssi
   
  before_script:
   - mvn -v
   - PFAD=$(pwd)
   - mkdir -p aptcache
   - apt-get update
   - apt-get -o dir::cache::archives="$PFAD/aptcache" install -y gawk --no-install-recommends
  script:
   - mvn $MAVEN_CLI_OPTS process-resources

documentation:branches:
  <<: *vorlage
  artifacts:
   paths:
    - target/html/
    - target/pdf/
   expire_in: 1 weeks
  except:
   - schedules

documentation:schedule:
  <<: *vorlage
  artifacts:
   paths:
    - target/html/
    - target/pdf/
   expire_in: 2 days
  only:
   - schedules
