include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

build:
  extends: .maven-build
  artifacts:
    expire_in: 1 day
    paths:
      - '**/target/doc/**'

stages:
  - build
