[[einleitung]]
= Einleitung

Dieses Handbuch dient technischen Autoren von IsyFact-Dokumenten als Wegweiser.

Festgelegte Ordnung::

IsyFact bietet eine geordnete Sammlung vielfältiger Dokumente, um die Entwicklung von IsyFact-basierenden Anwendungen zu beschreiben.
Für jeden Teilbereich, sei es für den Einstieg bis hin zur Nutzungsvorgabe einzelner Module, wird jeweils ein eigenes Dokument bereitgestellt.
Zur Vereinheitlichung werden alle Dokumente gemäß festgelegten Regeln und nach einem bestimmten Grundschema angefertigt.
Beispielsweise zeichnet sich jedes Dokument durch einen ähnlichen Aufbau aus, um dem Nutzer eine intuitive Handhabe zu gewährleisten.
Weil IsyFact häufig aktualisiert wird und immer mal wieder auch neue IsyFact-Module hinzugefügt werden,
müssen regelmäßig Änderungen in die vorhandenen Dokumente eingepflegt und auch stetig neue Dokumente zur Gesamtdokumentation beigefügt werden.
Dabei sollen nicht nur vorhandene Dokumente, sondern auch neue Dokumente dem gleichen Grundschema und derselben spezifizierten Form gerecht werden, damit die festgelegte Ordnung weiterhin beibehalten bleibt.

AsciiDoc::

Die IsyFact-Dokumentation wird in der vereinfachten Auszeichnungssprache AsciiDoc verfasst.
Eine AsciiDoc-Datei ist nicht binär, sondern besteht aus Klartext, ganz ohne proprietäre Technologie.
Einer der Vorteile der AsciiDoc-Syntax ist die leichte Erlernbarkeit, denn AsciiDoc benötigt denkbar wenige Markups.
AsciiDoc lässt sich zudem problemlos in moderne Versionsverwaltungssysteme integrieren, so dass alle Vorteile solcher Systeme wie z.B. paralleles Arbeiten in Branches, Pull/Merge Requests oder Continuous Integration nun auch auf Dokumente anwendbar sind.

Atom::

Für die Dokumentation der IsyFact wird Atom als Editor empfohlen.
Atom ist ein Open-Source-Texteditor, der von Github entwickelt wird. Neben den ausgereiften Plugins für die Bearbeitung von AsciiDoc-Dokumenten unterstützt Atom Git-basierte Projekte von Haus aus mit vielfältigen Funktionen.

Ausgabeformate HTML und PDF::

AsciiDoc-Dokumente können in verschiedenen Ausgabeformaten wie beispielsweise HTML oder PDF ausgegeben werden.
Bei der IsyFact-Dokumentation sorgen Skripte dafür, dass die erstellten HTML- und PDF-Dateien automatisch auch über ein Literaturverzeichnis, ein Glossar, ein Abbildungsverzeichnis und ein Tabellenverzeichnis verfügen.

[[aufbau-und-zweck-des-dokuments]]
= Aufbau und Zweck des Dokuments

Dieses Dokument ist eine Anleitung für technische Autoren.
Es ermöglicht ihnen, die vorhandene IsyFact-Dokumentation gemäß der festgelegten Ordnung zu aktualisieren und zu erweitern.
Gleichzeitig geht es auf die Besonderheiten ein, die bei der Verwendung der Auszeichnungssprache AsciiDoc im Rahmen der IsyFact-Dokumentation zu beachten sind.

Das Handbuch ist in folgende Bereiche untergliedert:

- Die Arbeitsumgebung einrichten
- Ein neues Dokument anlegen
- Ein existierendes Dokument bearbeiten