[[einleitung]]
== Einleitung

Bei der Softwareentwicklung werden Entwicklungsumgebungen (IDEs) wie Eclipse oder IntelliJ IDEA verwendet, welche die Anwendungsentwicklung in vielfältiger Weise unterstützen und effektiver gestalten.

Eine der unterstützenden Leistungen dieser IDEs ist die Erzeugung von Boilerplate Code für Konstruktoren, Getter/Setter und die Methoden `equals()` und `hashCode()`.

Während die Konstruktoren und Getter/Setter durch Eclipse und IntelliJ IDEA nach gleichem Muster generiert werden, bestehen bei der `equals()`- und `hashCode()` Generierung beider IDEs Unterschiede und es ergibt sich ein Handlungsbedarf, damit der Quellcode nicht je nach Einsatz einer IDE unterschiedlich generiert wird.

Eine weitere wichtige Funktion ist die einheitliche Formatierung des Quellcodes.
Auch hier ist die Maßgabe, dass der Quellcode nicht je nach Einsatz einer IDE unterschiedlich aussieht.
Dies kann, wenn in einem Team unterschiedliche IDEs verwendet werden, zu ständigen Wechseln der Formatierung führen, die sich in unnötig großen Commits ausdrücken.

Dieses Dokument beschreibt die Einrichtung und Verwendung dieser Funktionen wiefolgt:

Das Kapitel <<generierung-von-boilerplate-code>> beschäftigt sich mit der einheitlichen Generierung von Boilerplate Code, insbesondere mit der automatischen Erstellung der Methoden `equals()` und `hashCode()`. Unabhängig von der verwendeten Entwicklungsumgebung sollte der Code konform zum „general contract“ dieser beiden Methoden sein.

Nach einem kurzen Abschnitt zum technischen Hintergrund wird die Installation des Eclipse Plugins _jenerate_ <<jenerate>>
beschrieben . Für die Entwicklungsumgebung IntelliJ IDEA ist kein zusätzliches Plugin erforderlich, da der Hersteller die Codegenerierung auf Basis von `java.util.Objects` (seit Java 7) direkt anbietet.
Damit wird Softwareentwicklern ermöglicht, sowohl in der Entwicklungsumgebung Eclipse als auch in IntelliJ IDEA den gleichen Boilerplate Code für die `equals()` und `hashCode()` Methoden zu erstellen.

Das Kapitel <<formatierung-von-quellcode>> beschreibt die einheitliche Konfiguration und Verwendung der in Eclipse und IntelliJ IDEA eingebauten Code-Formatierer. Die Konfiguration hat zum Ziel, den Quellcode in beiden IDEs nahezu identisch formatiert zu formatieren. Das Kapitel schließt mit einer kurzen Diskussion der verbleibenden Unterschiede bei der Formatierung.