= Literaturverzeichnis: extern

// tag::inhalt[]
== externe Literatur/Links

Die folgende Auflistung zeigt alle für die IsyFact-Dokumentation verwendeten externen Links.

[[litextern-cc-licence]]
Creative-Commons-Lizenz::
https://creativecommons.org/licenses/by/4.0/legalcode.de

[[litextern-vorlageanwendung]]
IsyFact-Vorlageanwendung::
https://github.com/IsyFact/IsyFact-Vorlageanwendung

[[litextern-url-isyfact]]
IsyFact::
https://github.com/isyfact

[[litextern-string-latin-1-2]]
String Latin 1.2::
https://www.xoev.de/string-latin-4813

[[litextern-litextern-string-latin-1-2-download]]
String Latin 1.2 (Download)::
https://www.xoev.de/downloads-2316#StringLatin

[[litextern-cwe-502]]
CWE-502::
http://cwe.mitre.org/data/definitions/502.html

[[litextern-semantic-versioning]]
Semantic Versioning 2.0.0::
http://semver.org/spec/v2.0.0.html [Zugriff am 05.03.2018]

[[litextern-vermeulen2000]]
Allan Vermeulen, Scott W. Ambler, Greg Baumgardner, Eldon Metz, Trevor Misfeldt, Jim Shur, Patrick Thomson::
The Elements of Java Style. 2000. Cambridge University

[[litextern-ambler1999]]
Writing Robust Java Code. The AmbySoft Inc. Coding Standards for Java v17.01d::
http://www.ambysoft.com/downloads/javaCodingStandards.pdf

[[litextern-bloch2008]]
Joshua Bloch::
Effective Java Second Edition. 2008. Addison Wesley

[[litextern-virtual-box]]
Oracle VirtualBox::
https://www.virtualbox.org

[[litextern-osboxes]]
OSBoxes::
https://www.osboxes.org

[[litextern-osboxes-ubuntu]]
OSBoxes Ubuntu::
https://www.osboxes.org/ubuntu/

[[litextern-rpm-packaging-guide]]
RPM Packaging Guide::
https://rpm-packaging-guide.github.io/#what-is-a-spec-file

[[litextern-spring-tool-suite]]
Spring Tool Suite::
https://spring.io/tools

[[litextern-ubuntu-programmstarter]]
Ubuntu Desktop Programmstarter::
https://wiki.ubuntuusers.de/.desktop-Dateien/

[[litextern-apache]]
Apache::
http://www.apache.org

[[litextern-intellij]]
IntelliJ::
https://www.jetbrains.com/idea/

[[litextern-asciidoc]]
What is AsciiDoc? Why do we need it?::
https://asciidoctor.org/docs/what-is-asciidoc/

[[litextern-asciidoctor-usermanual]]
Asciidoctor User Manual::
https://asciidoctor.org/docs/user-manual/

[[litextern-asciidoc-syntax]]
AsciiDoc Syntax Quick Reference::
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

[[litextern-asciidoc-tutorial]]
Tutorial: Using AsciiDoc and Asciidoctor to write documentation::
http://www.vogella.com/tutorials/AsciiDoc/article.html

[[litextern-asciidoc-recommended-practices]]
AsciiDoc Recommended Practices::
https://asciidoctor.org/docs/asciidoc-recommended-practices

[[litextern-antora-installationen]]
Antora Installationen::
https://docs.antora.org/antora/latest/install-and-run-quickstart/

[[litextern-antora-playbook]]
Antora Playbook::
https://docs.antora.org/antora/latest/install-and-run-quickstart/#create-a-playbook

[[litextern-antora-maven]]
Antora mit Maven::
https://abelsromero.github.io/blog/2020/antora-with-maven.html

[[litextern-antora-xref-macro-structure]]
Antora: Xref macro structure::
https://docs.antora.org/antora/latest/page/xref/#structure

[[litextern-antora-komponente]]
Antora-Dokumentations-Komponente::
https://docs.antora.org/antora/latest/component-version-descriptor/

[[litextern-antora-verzeichnisstruktur]]
Antora-Verzeichnisstruktur::
https://docs.antora.org/antora/latest/standard-directories/

[[litextern-jsr-310]]
JSR 310 „Date and Time API“::
https://jcp.org/en/jsr/detail?id=310

[[litextern-maven-standard-directory-layout]]
Apache Maven Standard Directory Layout::
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

[[litextern-sun1997-code-conventions]]
Sun 1997::
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

[[litextern-synopse]]
Synopse::
http://de.wikipedia.org/wiki/Synopse

[[litextern-unix]]
Unix::
http://de.wikipedia.org/wiki/Unix

[[litextern-maven-central]]
Maven Central::
https://search.maven.org

[[litextern-eclipse-checkstyle-plugin]]
Eclipse Checkstyle Plugin::
https://github.com/checkstyle/eclipse-cs-update-site

[[litextern-git-lfs]]
Git LFS::
https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage

[[litextern-git]]
Git::
http://www.git-scm.com

[[litextern-jpa-hibernate]]
Java Persistence with Hibernate::
Christian Bauer, Gavin King
Java Persistence with Hibernate. 2007. Manning Publications

[[litextern-spring-data-jpa]]
Spring Data JPA::
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details

[[litextern-spring]]
Spring::
http://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/

[[litextern-spring-boot-properties-conversion]]
Spring Boot Dokumentation zu „Properties Conversion"::
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion

[[litextern-collection-mapping]]
Hibernate Documentation, Chapter 6. Collection Mapping::
http://www.hibernate.org/hib_docs/v3/reference/en/html/collections.html (Zugriff am 03.02.2022)

[[litextern-ucp]]
Universal Connection Pool for JDBC Developer’s Guide::
https://docs.oracle.com/cd/E11882_01/java.112/e12265/optimize.htm (Zugriff am 03.02.2022)

[[litextern-temporale-datenhaltung]]
Zeitmaschine – Temporale Datenhaltung::
https://web.archive.org/web/20040929014721/http://www.sigs.de/publications/js/2003/05/demelt_JS_05_03.pdf

[[litextern-it-grundschutz-bsi]]
IT-Grundschutz des BSI::
https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/it-grundschutz_node.html

[[litextern-it-grundschutz-m471]]
M 4.71 Restriktive Handhabung von Datenbank-Links::
https://download.gsb.bund.de/BSI/ITGSK/IT-Grundschutz-Kataloge_2016_EL15_DE.pdf Seite 3285 (Zugriff am 03.02.2022)

[[litextern-multitable-bulk-operations]]
Multitable Bulk Operations::
https://in.relation.to/2005/07/20/multitable-bulk-operations/  (Zugriff am 04.02.2022)

[[litextern-saga-4-0]]
SAGA 4.0::
https://www.cio.bund.de/SharedDocs/Publikationen/DE/Architekturen-und-Standards/SAGA/saga_4_0_download.pdf?__blob=publicationFile

[[litextern-saga-5]]
SAGA 5::
https://www.cio.bund.de/Web/DE/Architekturen-und-Standards/SAGA/SAGA%205-aktuelle%20Version/saga_5_aktuelle_version_node.html

[[litextern-webseiten-register-factory]]
Webseiten der Register Factory::
https://www.bva.bund.de/DE/Das-BVA/Aufgaben/I/Informationstechnik/RegisterFactory/Produkt/produkt_rf_node.html#doc241990bodyText6

[[litextern-register-factory]]
Register Factory::
http://www.register-factory.de

[[litextern-owasp]]
OWASP Top 10 Project::
https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project

[[litextern-hibernate-toolset-guide]]
Hibernate Toolset Guide::
http://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html_single/#toolsetguide

[[litextern-v-modell-xt]]
V-Modell XT::
http://www.cio.bund.de/v-modell-xt

[[litextern-slf4j-fatal]]
SLF4J FATAL::
http://slf4j.org/faq.html#fatal

[[litextern-slf4j-bridge-handler]]
SLF4JBridgeHandler::
http://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html

[[litextern-identity_management]]
Identity and Access Management::
https://en.wikipedia.org/wiki/Identity_management

[[litextern-architekturrichtlinie]]
Architekturrichtlinie für die IT des Bundes::
https://www.cio.bund.de/Web/DE/Architekturen-und-Standards/Architekturrichtlinie-IT-Bund/architekturrichtlinie_it_bund_node.html

[[litextern-oracle-globalization-support]]
Oracle, Globalization Support Guide 10g Release 2 (10.2)::
http://download.oracle.com/docs/cd/B19306_01/server.102/b14225.pdf

[[litextern-code2000]]
Code2000::
http://www.code2000.net

[[litextern-monitoring-systeme-unterstuetzt]]
unterstützte Monitoring-Systeme::
http://micrometer.io/docs/concepts#_supported_monitoring_systems

[[litextern-monitoring-systeme]]
Monitoring-Systeme::
http://micrometer.io/docs

[[litextern-spring-boot-info-endpoint]]
Dokumentation von Spring Boot zum Info-Endpoint::
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-application-info

[[litextern-diagrams-net]]
diagrams.net::
https://diagrams.net

[[litextern-diagrams-net-intellij]]
IntelliJ mit diagrams.net::
https://plugins.jetbrains.com/plugin/15635-diagrams-net-integration

[[litextern-diagrams-net-vs-code]]
Visualstudio mit diagrams.net::
https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio

[[litextern-asciidoctorj-extensions]]
AsciidoctorJ Extensions::
https://asciidoctor.org/docs/asciidoctorj

[[litextern-wiki-rest]]
Wikipedia-Seite zu REST::
https://de.wikipedia.org/wiki/Representational_State_Transfer

[[litextern-dissertation-roy-fielding]]
Dissertation von Roy Fielding::
https://www.ics.uci.edu/~fielding/pubs/dissertation/fielding_dissertation_2up.pdf

[[litextern-wikipedia-http-statuscode]]
Wikipedia-Seite zu HTTP-Statuscodes::
https://de.wikipedia.org/wiki/HTTP-Statuscode

[[litextern-restapitutorial-uebersicht-http-statuscodes]]
openapi-generator.tech::
https://www.restapitutorial.com/httpstatuscodes.html

[[litextern-openapi-generator-tech]]
Übersicht HTTP-Statuscodes::
https://openapi-generator.tech/docs/generators

[[litextern-swagger-request-validator]]
Swagger Request Validator::
https://bitbucket.org/atlassian/swagger-request-validator

[[litextern-spring-webflux-exceptions]]
Spring Homepage (Webflux Exceptions)::
https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-and-rest-exceptions

[[litextern-spring-oauth2-bearertoken-resolver]]
Spring Homepage (Bearer Token Resolver)::
https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/oauth2.html#oauth2resourceserver-bearertoken-resolver

[[litextern-spring-content-negotiation]]
Spring Homepage (Content Negotiation)::
https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/oauth2.html#oauth2resourceserver-bearertoken-resolver

[[litextern-oauth-homepage]]
OAuth Homepage::
https://oauth.net/2/

[[litextern-swagger-editor-intellij]]
Swagger Editor für IntelliJ::
https://plugins.jetbrains.com/plugin/14837-openapi-swagger-editor

[[litextern-swagger-editor-eclipse]]
Swagger Editor für Eclipse::
https://marketplace.eclipse.org/content/openapi-swagger-editor

[[litextern-swagger-spezification]]
Swagger Spezifikation::
https://swagger.io/specification/

[[litextern-font-awesome]]
Font Awesome::
https://fontawesome.com/

[id="litextern-font-awesome-icons"]
Font Awesome Icons::
https://fontawesome.com/icons/

[id="litextern-get-bootstrap"]
Get Bootstrap::
http://getbootstrap.com

[id="litextern-bootstrap-docs"]
Bootstrap Docs::
http://bootstrapdocs.com

[id="litextern-github-bootstrap-less"]
Bootstrap Less::
https://github.com/twbs/bootstrap/tree/master/less

[id="litextern-github-bootstrap-mini-js"]
Bootstrap Mini Js::
https://github.com/twbs/bootstrap/tree/master/js

[id="litextern-less-stylesheet"]
Less Stylesheet::
http://lesscss.org

[id="litextern-dot-less"]
dotLess::
http://www.dotlesscss.org

[id="litextern-less-app"]
Less.app::
http://incident57.com/less

[id="litextern-grunt-js"]
GruntJs::
http://gruntjs.com

[id="litextern-node-js"]
NodeJs::
http://nodejs.org

[id="litextern-get-bootstrap-grid"]
Get Bootstrap Grid::
http://getbootstrap.com/css/#grid

[id="litextern-eternicode-bootstrap-datepicker"]
Bootstrap Date Picker::
https://github.com/eternicode/bootstrap-datepicker/

[id="litextern-snapappointments-bootstrap-auswahlbox"]
Bootstrap Auswahlbox::
https://developer.snapappointments.com/bootstrap-select/

[id="litextern-jdewit-bootstrap-time-picker"]
Bootstrap Timepicker::
https://github.com/jdewit/bootstrap-timepicker/

[id="litextern-liberation-Font"]
Liberation Font::
https://github.com/liberationfonts/liberation-fonts

[id="litextern-ls-lint"]
JSLint::
http://www.jslint.com

[id="litextern-firefox-esr-roadmap"]
Firefox ESR Roadmap::
https://www.mozilla.org/en-US/firefox/organizations/faq/

[id="litextern-location-breadcrumb"]
Location Breadcrumb::
https://de.wikipedia.org/wiki/Brotkr%C3%BCmelnavigation

[id="litextern-juicystudio-kontrast-analyse"]
JuicyStudio Kontrast Analyse::
http://juicystudio.com/services/luminositycontrastratio.php

[id="litextern-paciellogroup-kontrast-analyse"]
Paciello Group Kontrast Analyse::
http://www.paciellogroup.com/resources/contrast-analyser.html#download

[id="litextern-vicheck"]
ViCheck::
http://www.vischeck.com/
// end::inhalt[]
