= Literaturverzeichnis: extern

// tag::inhalt[]
== externe Literatur/Links

Die folgende Auflistung zeigt alle für die IsyFact-Dokumentation verwendeten externen Links.

[id="litextern-cc-licence"]
Creative-Commons-Lizenz::
https://creativecommons.org/licenses/by/4.0/legalcode.de

[id="litextern-vorlageanwendung"]
IsyFact-Vorlageanwendung::
https://github.com/IsyFact/IsyFact-Vorlageanwendung

[id="litextern-url-isyfact"]
IsyFact::
https://github.com/isyfact

[id="litextern-string.latin-1.2"]
String Latin 1.2::
https://www.xoev.de/string-latin-4813

[id="litextern-string.latin-1.2-download"]
String Latin 1.2 (Download)::
https://www.xoev.de/downloads-2316#StringLatin

[id="litextern-CWE-502"]
CWE-502::
http://cwe.mitre.org/data/definitions/502.html

[id="litextern-SemanticVersioning"]
Semantic Versioning 2.0.0::
http://semver.org/spec/v2.0.0.html [Zugriff am 05.03.2018]

[id="litextern-Vermeulen2000"]
Allan Vermeulen, Scott W. Ambler, Greg Baumgardner, Eldon Metz, Trevor Misfeldt, Jim Shur, Patrick Thomson::
The Elements of Java Style. 2000. Cambridge University

[id="litextern-Ambler1999"]
Writing Robust Java Code. The AmbySoft Inc. Coding Standards for Java v17.01d::
http://www.ambysoft.com/downloads/javaCodingStandards.pdf

[id="litextern-Bloch2008"]
Joshua Bloch::
Effective Java Second Edition. 2008. Addison Wesley

[id="litextern-VirtualBox"]
Oracle VirtualBox::
https://www.virtualbox.org

[id="litextern-OSBoxes"]
OSBoxes::
https://www.osboxes.org

[id="litextern-OSBoxes-Ubuntu"]
OSBoxes Ubuntu::
https://www.osboxes.org/ubuntu/

[id="litextern-RPM-Packaging-Guide"]
RPM Packaging Guide::
https://rpm-packaging-guide.github.io/#what-is-a-spec-file

[id="litextern-SpringToolSuite"]
Spring Tool Suite::
https://spring.io/tools

[id="litextern-Ubuntu-Programmstarter"]
Ubuntu Desktop Programmstarter::
https://wiki.ubuntuusers.de/.desktop-Dateien/

[id="litextern-Apache"]
Apache::
http://www.apache.org

[id="litextern-VisualStudio"]
Visual Studio::
https://code.visualstudio.com/

[id="litextern-Atom"]
Atom::
https://atom.io/

[id="litextern-IntelliJ"]
IntelliJ::
https://www.jetbrains.com/idea/

[id="litextern-Maven"]
Maven::
https://maven.apache.org/download.cgi

[id="litextern-AsciiDoc"]
What is AsciiDoc? Why do we need it?::
https://asciidoctor.org/docs/what-is-asciidoc/

[id="litextern-AsciidoctorUserManual"]
Asciidoctor User Manual::
https://asciidoctor.org/docs/user-manual/

[id="litextern-AsciiDocSyntax"]
AsciiDoc Syntax Quick Reference::
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

[id="litextern-AsciiDocTutorial"]
Tutorial: Using AsciiDoc and Asciidoctor to write documentation::
http://www.vogella.com/tutorials/AsciiDoc/article.html

[id="litextern-AsciiDocRecommendedPractices"]
AsciiDoc Recommended Practices::
https://asciidoctor.org/docs/asciidoc-recommended-practices

[id="litextern-AntoraXrefMacroStructure"]
Antora: Xref macro structure::
https://docs.antora.org/antora/latest/page/xref/#structure

[id="litextern-JSR-310"]
JSR 310 „Date and Time API“::
https://jcp.org/en/jsr/detail?id=310

[id="litextern-Maven-Standard-Directory-Layout"]
Apache Maven Standard Directory Layout::
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

[id="litextern-Sun1997-Code-Conventions"]
Sun 1997::
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

[id="litextern-Synopse"]
Synopse::
http://de.wikipedia.org/wiki/Synopse

[id="litextern-Unix"]
Unix::
http://de.wikipedia.org/wiki/Unix

[id="litextern-Maven-Central"]
Maven Central::
https://search.maven.org

[id="litextern-Eclipse-Checkstyle-Plugin"]
Eclipse Checkstyle Plugin::
https://github.com/checkstyle/eclipse-cs-update-site

[id="litextern-Git-LFS"]
Git LFS::
https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage

[id="litextern-Git"]
Git::
http://www.git-scm.com

[id="litextern-JPA-Hibernate"]
Java Persistence with Hibernate::
Christian Bauer, Gavin King
Java Persistence with Hibernate. 2007. Manning Publications

[id="litextern-Spring-Data-JPA"]
Spring Data JPA::
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details

[id="litextern-Spring"]
Spring::
http://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/


[id="litextern-Spring-Boot-Properties-Conversion"]
Spring Boot Dokumentation zu „Properties Conversion"::
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion

[id="litextern-Collection-Mapping"]
Hibernate Documentation, Chapter 6. Collection Mapping::
http://www.hibernate.org/hib_docs/v3/reference/en/html/collections.html (Zugriff am 03.02.2022)

[id="litextern-UCP"]
Universal Connection Pool for JDBC Developer’s Guide::
https://docs.oracle.com/cd/E11882_01/java.112/e12265/optimize.htm (Zugriff am 03.02.2022)

[id="litextern-Temporale-Datenhaltung"]
Zeitmaschine – Temporale Datenhaltung::
https://web.archive.org/web/20040929014721/http://www.sigs.de/publications/js/2003/05/demelt_JS_05_03.pdf

[id="litextern-IT-Grundschutz-BSI"]
IT-Grundschutz des BSI::
https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/it-grundschutz_node.html

[id="litextern-IT-Grundschutz-M471"]
M 4.71 Restriktive Handhabung von Datenbank-Links::
https://download.gsb.bund.de/BSI/ITGSK/IT-Grundschutz-Kataloge_2016_EL15_DE.pdf Seite 3285 (Zugriff am 03.02.2022)

[id="litextern-Multitable-Bulk-Operations"]
Multitable Bulk Operations::
https://in.relation.to/2005/07/20/multitable-bulk-operations/  (Zugriff am 04.02.2022)

[id="litextern-SAGA_4.0"]
SAGA 4.0::
https://www.cio.bund.de/SharedDocs/Publikationen/DE/Architekturen-und-Standards/SAGA/saga_4_0_download.pdf?__blob=publicationFile

[id="litextern-SAGA_5"]
SAGA 5::
https://www.cio.bund.de/Web/DE/Architekturen-und-Standards/SAGA/SAGA%205-aktuelle%20Version/saga_5_aktuelle_version_node.html

[id="litextern-Semantic-Versioning"]
Semantic Versioning::
https://semver.org

[id="litextern-Webseiten-Register-Factory"]
Webseiten der Register Factory::
https://www.bva.bund.de/DE/Das-BVA/Aufgaben/I/Informationstechnik/RegisterFactory/Produkt/produkt_rf_node.html#doc241990bodyText6

[id="litextern-Register-Factory"]
Register Factory::
http://www.register-factory.de

[id="litextern-OWASP"]
OWASP Top 10 Project::
https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project

[id="litextern-Hibernate-Toolset-Guide"]
Hibernate Toolset Guide::
http://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html_single/#toolsetguide

[id="litextern-v-modell-xt"]
V-Modell XT::
http://www.cio.bund.de/v-modell-xt

[id="litextern-slf4j-fatal"]
SLF4J FATAL::
http://slf4j.org/faq.html#fatal

[id="litextern-slf4j-bridge-handler"]
SLF4JBridgeHandler::
http://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html

[id="litextern-Identity_management"]
Identity and Access Management::
https://en.wikipedia.org/wiki/Identity_management

[id="litextern-Architekturrichtlinie"]
Architekturrichtlinie für die IT des Bundes::
https://www.cio.bund.de/Web/DE/Architekturen-und-Standards/Architekturrichtlinie-IT-Bund/architekturrichtlinie_it_bund_node.html

[id="litextern-Oracle-Globalization-Support"]
Oracle, Globalization Support Guide 10g Release 2 (10.2)::
http://download.oracle.com/docs/cd/B19306_01/server.102/b14225.pdf

[id="litextern-Code2000"]
Code2000::
http://www.code2000.net

[id="litextern-Monitoring-Systeme-unterstützt"]
unterstützte Monitoring-Systeme::
http://micrometer.io/docs/concepts#_supported_monitoring_systems

[id="litextern-Monitoring-Systeme"]
Monitoring-Systeme::
http://micrometer.io/docs

[id="litextern-Spring-Boot-Info-Endpoint"]
Dokumentation von Spring Boot zum Info-Endpoint::
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-application-info

[id="litextern-diagrams.net"]
diagrams.net::
https://diagrams.net

[id="litextern-diagrams.net-IntelliJ"]
IntelliJ mit diagrams.net::
https://plugins.jetbrains.com/plugin/15635-diagrams-net-integration

[id="litextern-diagrams.net-VS-Code"]
Visualstudio mit diagrams.net::
https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio
// end::inhalt[]
