= Änderungen an Inhalten

include::glossary:licence:partial$licence.adoc[]

Der Leitfaden bietet die Möglichkeit an, Änderungen an Inhalten über vordefinierte https://docs.asciidoctor.org/asciidoc/latest/blocks/sidebars/[Sidebars] anzuzeigen.
Er unterstützt die Auszeichnung von Inhalten in Erstellung und in Überarbeitung.


[[erstellung]]
== Inhalte in Erstellung

Wenn Inhalte neu erstellt werden, geschieht dies meist über einen längeren Zeitraum hinweg.
Während der Erstellung sind diese neuen Inhalte in der Regel noch nicht in der ganzen IsyFact berücksichtigt.

Um solche Inhalte auszuzeichnen, bietet der Leitfaden drei Varianten an: eine allgemeine, eine für Seiten und eine für Bausteine.
Es sollte immer die Variante gewählt werden, die am besten zum Wirkungsbereich (_Scope_) der Änderung passt.

=== Allgemeine Sidebar

include::partial$content-new.adoc[]

=== Sidebar für Seiten

include::partial$content-new-page.adoc[]

=== Sidebar für Bausteine

include::partial$content-new-building-block.adoc[]


[[ueberarbeitung]]
== Inhalte in Überarbeitung

//Wenn Inhalte neu erstellt werden, geschieht dies meist über einen längeren Zeitraum hinweg.
//Während der Erstellung sind diese neuen Inhalte in der Regel noch nicht in der ganzen IsyFact berücksichtigt.

Um solche Inhalte auszuzeichnen, bietet der Leitfaden drei Varianten an: eine allgemeine, eine für Seiten und eine für Bausteine.
Es sollte immer die Variante gewählt werden, die am besten zum Wirkungsbereich (_Scope_) der Änderung passt.

=== Allgemeine Sidebar

include::partial$content-revised.adoc[]

=== Sidebar für Seiten

include::partial$content-revised-page.adoc[]

=== Sidebar für Bausteine

include::partial$content-revised-building-block.adoc[]


== Kurzform
//  Kurzform für Tabellen oder ähnliche Textstellen

icon:puzzle-piece[title="Work in Progress"] <durchzustreichender Titel/Text>