= Versionierung von Inhalten

include::glossary:licence:partial$licence.adoc[]

Jeder Inhalt der Online-Dokumentation ist Teil genau einer Antora-Komponente.
Antora-Komponenten legen ihre Version in ihrer Konfigurationsdatei fest.
Dieser Guide beschreibt, auf welche Art dies geschieht.

NOTE: Für diesen Guide ist ein grundlegendes Verständnis der https://docs.antora.org/antora/latest/component-version-descriptor/[Konfigurationsdatei `antora.yml`] nützlich.

[[versionierung-vorgehensweise]]
== Vorgehensweise

Die Online-Dokumentation der IsyFact verwendet zwei Arten der Versionierung: Spiegeln der Software-Version und das explizite Ausnehmen von der Versionierung.

[[komponente-mit-software-version]]
=== Spiegeln der Software-Version

Wenn Antora-Komponenten zusammen mit Software-Komponenten veröffentlicht werden, spiegeln sie deren Version.
Beispiele hierfür sind der xref:isy-angular-widgets-doc::konzept/konzept.adoc[Baustein Angular] und die xref:isyfact-standards-doku:einstieg:einstieg.adoc[IsyFact-Standards].

Aktuell gibt es zwei Vorgehensweisen:

* Bei kurzen Release-Zyklen enthält die Online-Dokumentation ausschließlich offizielle Releases einer Antora-Komponente.
* Bei längeren Release-Zyklen beinhaltet die Online-Dokumentation auch einen Entwicklungsstand, damit sich die Nutzer der IsyFact auf die Änderungen des nächsten Releases vorbereiten können.

Unabhängig von der Vorgehensweise müssen zur Versionierung mehrere Parameter in der Konfigurationsdatei `antora.yml` gesetzt werden:

* `version`: https://docs.antora.org/antora/latest/component-version-key/[Version] der Antora-Komponente,
* `display_version`: (optional) https://docs.antora.org/antora/latest/component-display-version/[Version zur Anzeige] im UI,
* `prerelease`: (optional) Anzeige eines https://docs.antora.org/antora/latest/component-prerelease/[Entwicklungsstands].

Ob und wie die Parameter zu setzen sind, erklärt der Abschnitt <<konfiguration-version>>.

[[komponente-ohne-version]]
=== Explizites Ausnehmen von der Versionierung

Wenn die Inhalte der Antora-Komponente keine Versionierung benötigen, weil sie stets widerspiegeln, was zum aktuellen Zeitpunkt gilt, werden sie explizit von der Versionierung ausgenommen.
Beispiele hierfür sind dieser xref:index.adoc[Leitfaden] sowie das xref:glossary:glossary:master.adoc[].

NOTE: Für solche Inhalte sieht Antora das Konzept einer https://docs.antora.org/antora/latest/component-with-no-version/[Komponente ohne Version] vor.

Die Konfiguration einer solchen Antora-Komponente ist denkbar einfach.

.Antora-Komponente ohne Version
[source,yaml]
----
version: ~
----

TIP: Antora-Komponenten ohne Version durchlaufen keine Releases und sollten daher nicht in einem Git-Repository liegen, für das Releases erstellt werden.

[[konfiguration-version]]
== Konfiguration der Version

Antora ermöglicht es, Versionsnummern explizit festzulegen, oder die Version anhand der konfigurierten Git-Referenz (Branch oder Tag) zu setzen.

[[versionierung-git]]
=== Versionierung mittels Git-Referenz

Die Versionierung mithilfe der Git-Referenz ist dann sinnvoll, wenn eine Antora-Komponente über Tags versioniert wird oder die Branch-Namen eine gute Vorlage für die Version bieten.

.Versionierung mittels Git-Referenz
[source,yaml]
----
version: true
----

Antora kürzt die Git-Referenz folgendermaßen ab:

* aus `refs/heads/main` wird `main`,
* aus `refs/tags/v1.0rc4` wird `v1.0rc4`.

Reicht dieses einfache Mapping nicht aus, kann Antora auch https://docs.antora.org/antora/latest/component-version-key/#refname-projection[komplexere Ersetzungen] auf der Git-Referenz vornehmen.

IMPORTANT: Bei diesem Vorgehen ist es nicht sinnvoll, eine abweichende `display_version` zu setzen, da sich diese nicht im Einklang mit dem Wert von `version` ändert.

[[explizite-versionierung]]
=== Explizite Versionierung

Ist eine Versionierung über die Git-Referenz nicht sinnvoll, muss die Version explizit festgelegt werden.
Die Version entspricht, wie in der IsyFact vorgeschrieben, dem Format nach xref:4.0.x@isyfact-standards-doku:methodik:versionierung/master.adoc[Semantic Versioning].

.Explizite Versionierung
[source,yaml]
----
version: '4.0.3'
----

Sollen Bugfix-Releases nicht zu einer Versionsänderung in der Dokumentation führen, kann diese davon abstrahieren.

.Explizite Versionierung ohne Bugfix-Release
[source,yaml]
----
version: '4.0.x'
----

[[version-auszeichung]]
=== Auszeichnung spezieller Versionen

Versionen mit spezieller Bedeutung sind mit einem Suffix zu kennzeichnen.

.Auszeichnung spezieller Versionen
[cols="2,1m",options="header"]
|===
| Art der Version
| Suffix

| Aktuelle Version
| CURRENT

| LTS-Version
| LTS

| Entwicklungsstand
| DEV
|===

Für aktuelle Versionen und LTS-Versionen geschieht die Kennzeichnung über die `display_version`.
Der Wert von `version` ist Bestandteil von Verweisen und sollte deswegen möglichst stabil bleiben.

[[explizite-versionierung-speziell]]
.Explizite Versionierung mit spezieller Auszeichnung
[source,yaml]
----
version: '4.0.3'
display_version: '4.0.3 (LTS)'
----

IMPORTANT: Diese Konfiguration funktioniert aufgrund der Dopplung der Versionsnummer nicht gut für die Versionierung über Git-Referenzen.

[[version-entwicklung]]
==== Auszeichnung von Entwicklungsständen

Für Entwicklungsstände gibt es eine weitere Möglichkeit der Konfiguration, bei dem die Version nicht, wie im <<explizite-versionierung-speziell,vorigen Beispiel>>, in der Konfiguration dupliziert werden muss.

.Konfiguration einer Entwicklungsversion (explizit)
[source,yaml]
----
version: '4.0.3'
prerelease: '(DEV)'
----

Aus dieser Konfiguration heraus setzt Antora die `display_version` auf den Wert `4.0.3 (DEV)`.

Entwicklungsstände können so auch ausgezeichnet werden, wenn die Versionierung über Git-Referenzen erfolgt.
