= Projektseite erzeugen

include::glossary:licence:partial$licence.adoc[]

Die Generierung einer Projektseite erfolgt, falls das Repository https://github.com/IsyFact/isyfact.github.io[icon:github[] isyfact.github.io] verwendet wird, wie in vergleichbaren npm-Projekten.
Nachdem alle Abhängigkeiten installiert wurden, wird die Projektseite mit dem Befehl `npm build` erzeugt.

== Aufbau des Playbooks

Die offizielle Antora-Dokumentation beschreibt das https://docs.antora.org/antora/latest/install-and-run-quickstart/#create-a-playbook[Playbook].
Deshalb wird hier nur auf die IsyFact-Besonderheiten eingegangen.

[[listing-playbook]]
.Playbook der Online-Dokumentation
[source,yaml]
----
site:
  title: IsyFact
  url: https://isyfact.github.io/
  start_page: isyfact-standards-doku:einstieg:einstieg.adoc
content:
  sources:
    # ... <.>
runtime:
  fetch: true
asciidoc:
  attributes:
    page-toctitle: Inhalt
    sectnums: true             <.>
    sectnumlevels: 5           <.>
    caution-caption: Achtung   <.>
    important-caption: Wichtig
    note-caption: Hinweis
    tip-caption: Tipp
    warning-caption: Warnung
    appendix-caption: Anhang
    example-caption: Beispiel
    figure-caption: Abbildung
    table-caption: Tabelle
    listing-caption: Listing
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable <.>
    snapshot: true
  supplemental_files: ./supplemental-ui <.>
output:
  dir: ./docs
----
<.> Die Einbindung von Antora-Komponenten beschreibt der Guide "xref:content-sources.adoc[]".
<.> Abschnitte sollen nummeriert werden.
<.> Die Abschnitte dürfen bis Level 5 geschachtelt sein (möglich, aber nicht empfohlen).
<.> Vordefinierte Captions auf Deutsch.
<.> Standard-UI von Antora.
<.> Ergänzungen der IsyFact zum Standard-UI.

== Supplemental UI

Unter dem im Playbook unter `supplemental_files` angegebenen Pfad kann das Standard-UI von Antora leicht mit CSS und JavaScript überschrieben werden.
Dies sollte jedoch nur bei kleineren Änderungen genutzt werden, bei größeren Änderungen empfiehlt es sich, ein eigenes UI zu schreiben, ggf. auf Basis des Standard-UIs.
