[[maven-plugin-versionierungskontrolle]]
= IsyFact Maven-Plugin zur Versionierungskontrolle

Zur Sicherstellung einer validen Versionierung der Anwendung wird das Maven-Plugin isy-versioning-maven-plugin eingesetzt.
Um das Maven-Plugin zu nutzen, muss es in die `pom.xml` integriert werden. Dies ist unter <<einbindung-konfiguration>> erläutert.

[[funktionweise]]
== Funktionsweise
Das Maven-Plugin prüft beim Build-Vorgang, ob die angegebene Version den Versionierungsvorgaben in <<IsyFact-Versionierung>> entspricht. Die Versionsangabe wird in der Lifecycle-Phase "validate" geprüft. Dies ist im Default-Lifecycle der erste Schritt.

Die Versionierung ist abhängig von der Art der Komponente. Aus diesem Grund wird bei der Validierung zwischen Geschäftsanwendungen und Schnittstellen unterschieden. Dabei wird zunächst von jeder Komponente angenommen, es verfolgt die Versionierungsrichtlinien von Geschäftsanwendungen. Konnten diese nicht nachgewiesen werden, wird automatisch geprüft, ob die Kritierien einer Schnittstellen-Version auf die Versionsnummer zutreffen.


*Anwendungen*

Die Versionskontrolle der Geschäftsanwendungen und Register findet über reguläre Ausdrücke statt. Dabei wird zwischen zwei Szenarien unterschieden:

Release-Version: Eine stabile Version, welche zum Produktiv-Einsatz gedacht ist. Dort sind nur die Komponenten *`<major>.<minor>.<patch>`* erlaubt.

Test-Version: Eine Version, welche für eine Testumgebung gedacht ist. Die Stabilität dieser Version ist nicht sichergestellt. Dort sieht der Aufbau wie folgt aus: *`<major>.<minor>.<patch>[-<label>][+<buildmetadaten>]`*

Die Art des Szenarios, das für die zu kompilierende Anwendung genutzt werden soll, kann in der Anwendung selbst definiert werden. Siehe Konfiguration in der Anwendung.


*Schnittstellen*

Schnittstellen enthalten die *`<major>.<minor>`*-Version bereits in ihrer Modul-Bezeichnung. Aus diesem Grund enthält die Schnittstelle nur noch die *`<patch>`*-Version als Versionsnummer. Bei Test-Versionen wird die Version noch um ein Label erweitert (*`<patch>[-<label>]`*).

[[einbindung-konfiguration]]
== Einbindung und Konfiguration in der Anwendung

Das Maven-Plugin wird in der `pom.xml` des Projekts wie folgt hinterlegt:

[source,xml]
-----------------
...
    <plugin>
        <groupId>de.bund.bva.isyfact</groupId>
        <artifactId>isy-versioning-maven-plugin</artifactId>
        <version>1.0.0-RC1</version>
        <configuration>
            <!-- Schalter zum Deaktivieren des Plugins.  -->
            <enabled>true</enabled>
            <!-- Erlaubt das Ausschließen von Test-Versionen. -->
            <release>false</release>
        </configuration>
        <executions>
            <execution>
                <id>validateVersion</id>
                <phase>validate</phase>
                <goals>
                    <goal>validateVersion</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
...
-----------------

Über die Verwendung der Konfigurationsparamater `enabled` und `release` kann das Maven-Plugin gesteuert werden:

[options="header"]
|=======================
|Konfigurationsparameter|Beschreibung|Standard|Beispiel
|*`enabled`*|Definiert, ob das Plugin verwendet (`true`) oder deaktiviert (`false`) werden soll.|`true`|`true`
|*`release`*|Definiert, ob das Szenario ein Release (`true`) oder ein Build (`false`) ist.|`true`|`true`
|=======================

Zusätzlich kann mittels der Maven-Konsole die Konfigurationsparameter mit einem vorgelagerten `-D` an das Plugin übergeben werden, um während des Build-Prozess Einfluss auf das Plugin-Verhalten zu erwirken.
[source]
-----------------
-DVersionValidatorEnabled=true/false
-DVersionValidatorRelease=true/false
-----------------