[[ueberwachung-von-anwendungen]]
= Überwachung von Anwendungen

In diesem Kapitel werden die Anforderungen an die Überwachung von Anwendungen beschrieben.
Der Fokus liegt dabei auf der Schaffung von einheitlichen Administrationsschnittstellen, welche dem Betrieb eine einfache Überwachung der Anwendungen erlauben.
Alle Vorgaben sind beim Entwurf und der Realisierung von neuen Anwendungen nach IsyFact-Architektur zu berücksichtigen.
Gegebenenfalls können in Systementwürfen Verfeinerungen der hier getroffenen Vorgaben gemacht werden.
Weiterhin können die hier gemachten Vorgaben als Basis für die Beschreibung der Überwachungsschnittstelle im Betriebshandbuch der Anwendungssysteme verwendet werden.

[[kurzeinfuehrung-in-das-system-monitoring-mit-spring-boot-actuator]]
== Kurzeinführung in das System-Monitoring mit Spring Boot Actuator

Spring Boot bringt mit Actuator eine Reihe zusätzlicher Funktionen mit, die dabei helfen, Anwendungen zu überwachen und zu verwalten.
Die Kommunikation mit der Anwendung erfolgt über sogenannte _Endpoints_.
Diese können über HTTP oder JMX bereitgestellt werden.
Actuator bringt eine Reihe von eingebauten Endpoints mit und bietet auch die Möglichkeit, eigene Endpoints hinzuzufügen.
So wird für Informationen über den Systemzustand der eingebauten Endpoint `health` angeboten und über den Endpoint `metrics` können Metriken gelesen werden.

[[micrometer]]
=== Micrometer

Die im Endpoint `metrics` bereitgestellen Metriken werden von Micrometer erfasst.
Micrometer bietet eine einfache anbieterneutrale Fassade für die gängigsten Überwachungssysteme und ermöglicht es, Metriken im Anwendungscode ohne Herstellerbindung zu implementieren.
Seit Spring Boot 2.0 ist Micrometer die Standardbibliothek zur Bereitstellung von Anwendungsmetriken von Spring.

NOTE: Für eine Liste der unterstützten Monitoring-Systeme siehe http://micrometer.io/docs/concepts#_supported_monitoring_systems

[[festlegungen-und-ausgrenzungen]]
== Festlegungen und Ausgrenzungen

Die Nutzungsvorgaben finden sich im dem Dokument <<NutzungsvorgabenUeberwachungKonfiguration>>.

Das Konzept für die Prüfung der Verfügbarkeit ist:

* Anwendungen nach IsyFact-Architektur sollen Mechanismen bereitstellen, die es erlauben, die Verfügbarkeit der Anwendung durch eine betriebliche Überwachung zu prüfen.
* Grundlage dafür ist die Bereitstellung eines `HealthIndicators` und einer Ping-Methode durch die Anwendung.

Folgende Punkte sind bewusst nicht Teil dieses Konzeptes:

* Die Konfiguration eines konkreten Produkts zum System-Monitoring ist nicht Teil des Konzeptes.
* Micrometer unterstützt die Anbindung zahlreicher Monitoring-Systeme.
  Es werden keine Vorgaben zur Verwendung eines bestimmten Systems gemacht.

[[vorgaben-fuer-konfigurationen]]
= Vorgaben für Konfigurationen

In diesem Kapitel wird das Konzept der Konfigurationen für Anwendungen nach der IsyFact-Architektur beschrieben.

Für das Verständnis ist es wichtig die Konfigurationsparameter von den konkreten Parameterwerten für diese Konfigurationsparameter zu unterscheiden.
Erstere sind fest von der Anwendungsimplementierung vorgegeben.
Die Anwendung legt z.B. fest, dass es einen Parameter `datenbank.kennwort` zur Festlegung des Datenbankkennworts gibt.
Parameterwerte meinen die Einstellungen für diese Parameter und werden z.B. vom Betrieb konfiguriert.
Als Konfiguration wird die Menge aller Konfigurationsparameter einer Anwendung verstanden.

[[festlegungen-und-ausgrenzungen-1]]
== Festlegungen und Ausgrenzungen

* Das Konfigurationskonzept betrifft alle von den IsyFact-Anwendungen verwendeten Konfigurationen.
  Dazu gehören sowohl vom Betrieb zu pflegende Konfigurationsdateien, als auch statische Konfigurationen, die z.B. das Layout von Dialog-Masken beschreiben (Ressource-Dateien).
  Wenn im Folgenden von Konfigurationen gesprochen wird, sind sowohl Konfigurationen im eigentlichen Sinne, als auch Ressourcen gemeint.
* Anwendungen müssen im Normalfall für Konfigurationsänderungen neu gestartet werden.
  Ausnahmen hiervon bedürfen besonderer technischer und organisatorischer Maßnahmen.
  Details dazu werden in dem Dokument <<NutzungsvorgabenUeberwachungKonfiguration>> beschrieben.
* Das Konfigurationskonzept berücksichtigt sowohl die Konfiguration für die Entwicklungsumgebung als auch geeignete Vorgehensweisen für die Konfiguration der Produktionsumgebung.
* Alle Anwendungssysteme und Batches, die schreibend auf eine andere Fachanwendung zugreifen, müssen auf die Nichtverfügbarkeit dieser Komponente vorbereitet sein.
  Entweder können jene Systeme vorübergehend heruntergefahren sein, oder bestimmte Funktionen, z.B. der Schreibzugriff, können über Konfigurationsparameter deaktiviert sein.
  Systeme, bei denen Funktionen deaktiviert sind, zeigen Benutzern frühzeitig einen Hinweis an, welche Funktionen nicht zur Verfügung stehen.
  Ob eine Anwendung einen Konfigurationsparameter erhält oder heruntergefahren werden kann, muss für jede Anwendung, abhängig von deren Verfügbarkeitsanforderung, individuell entschieden werden.

[[typisierung-und-handhabung-von-konfigurationen]]
== Typisierung und Handhabung von Konfigurationen

Eine Einordnung der Konfigurationen ist für das Deployment und den Betrieb einer Anwendung notwendig.
Nur so ist sichergestellt, dass z.B. Parameterwerte für die Produktion nicht schon während des Bauens der Anwendung bekannt sein müssen.
Außerdem wird gewährleistet, dass die jeweilige verantwortliche Personengruppe einen leichten Zugriff auf „ihre“ Konfigurationsparameter erhält.

Das wichtigste Kriterium ist, ob die betreffende Konfiguration für alle Umgebungen (Ziel-Systeme) identisch ist, und die Fragestellung, von wem die Konfiguration angepasst wird.
Grundsätzlich kommen dafür Entwickler, der Betrieb oder die Fachabteilung in Frage.

Konfigurationen lassen sich wie in <<table-typKonfZiel2>> dargestellt typisieren:

Die Spalte „Pflegeverantwortung“ gibt an, wer die entsprechenden Konfigurationen pflegt.
So wird beispielsweise die Spring-Konfiguration ausschließlich von den Anwendungsentwicklern bearbeitet.
Die Konfiguration ist statisch, d.h. sie ist schon zur Entwicklungszeit bekannt und auch nach der Installation nicht mehr veränderbar.

Der Spalte „Umgebungsabhängigkeit erlaubt“ lässt sich entnehmen, ob der entsprechende Konfigurationstyp für eine bestimmte Umgebung (d.h. Testumgebungen, Produktionsumgebung) spezifische Teile enthalten darf.
So dürfen von Entwicklern zu pflegende Konfigurationen niemals umgebungsabhängig sein.
Wäre dies der Fall müsste, beispielsweise ein Entwickler das Kennwort der Produktionsdatenbank kennen.

Die Spalte „Erlaubte Zugriffsart der Anwendung“ gibt an, ob der entsprechende Konfigurationstyp von der Anwendung nur gelesen oder auch geschrieben werden darf.
Die wenigsten Konfigurationen sollten durch die Anwendung selbst geschrieben werden.
Lediglich Benutzerkonfigurationen werden typischerweise zur Laufzeit der Anwendung dynamisch geändert.
Diese müssen in der Datenbank gespeichert werden.

Die letzte Spalte der Tabelle gibt die bevorzugte Art für die Speicherung der entsprechenden Konfiguration an.

So müssen betriebliche Konfigurationen leicht durch den Betrieb zugänglich und änderbar sein.

Für Details siehe das Dokument <<NutzungsvorgabenUeberwachungKonfiguration>>.

:desc-table-typKonfZiel2: Typisierung von Konfigurationen nach Zielgruppen
[id="table-typKonfZiel2",reftext="{table-caption} {counter:tables}"]
.{desc-table-typKonfZiel2}
[cols="5,3,3,3",options="header"]
|====
h|Konfigurationstyp |Statische Konfiguration |Betriebliche Konfiguration |Benutzer-Konfiguration
h|Pflegeverantwortung |Entwickler |Betrieb |Fachabteilung oder Administratoren
h|Beispiel 	|Spring-Konfiguration |Datenbank-Benutzer und -Kennwort |Dialog-Einstellungen
h|Umgebungsabhängigkeit erlaubt |nein |ja |nein
h|Erlaubte Zugriffsarten der Anwendung |nur lesend |nur lesend |lesend und schreibend
h|Speicherung|Als Datei im Resources-Ordner |Als Property-Datei im Config-Ordner |In der Datenbank
|====
