[[Einleitung]]
== Einleitung

Dieses Dokument enthält das technische Feinkonzept zur Überwachung und Konfiguration von Anwendungen gemäß den IsyFact-Standards.

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

In diesem Dokument werden die Designvorgaben für die Überwachung und die Handhabung von Konfigurationen für Anwendungen
gemäß der IsyFact-Referenzarchitektur vorgestellt <<IsyFact-Referenzarchitektur>>. Gleichzeitig
werden konkrete Nutzungskonzepte und
Implementierungsvorgaben beschrieben.

Die Realisierung einer einheitlichen Überwachungsschnittstelle erlaubt es dem Betrieb frühzeitig Probleme in der
Anwendungslandschaft zu erkennen und darauf zu reagieren.
Dadurch können Ausfallzeiten minimiert werden.

Die Vereinheitlichung der Konfiguration erleichtert nicht nur die Entwicklung der Anwendungen, sondern stellt
vor allem eine Erleichterung des Betriebs der Anwendungen da.

Alle Vorgaben orientieren sich an den in den jeweiligen Kapiteln aufgeführten Anforderungen und gelten für alle
Anwendungen nach IsyFact-Architektur.
