= Nutzungsvorgaben HTTP Invoker: Einleitung
include::{isy-dokumentvorlagen}/docs/common/isyfact-attributes.adoc[]

// tag::inhalt[]
[[einleitung]]
== Einleitung

[NOTE]
====
Dieses Dokument ist aus mehreren Quellen entstanden und fasst die vorhandene Dokumentation zum Thema HTTP Invoker zusammen.
Der Baustein HTTP Invoker steht unter Bestandsschutz und wird nicht mehr aktiv weiterentwickelt.
Er wird in einem der nächsten Major Releases aus der IsyFact entfernt.
// TODO Links zum REST-Konzept einfügen.
====

Das Dokument <<KonzeptHttpInvoker>> konzentriert sich auf die konzeptionellen Aspekte von Services mit HTTP Invoker.

Dieses Dokument beschreibt, wie diese Services konkret umgesetzt werden.
Es richtet sich an Entwickler, die ein <<glossar-IT-System>> gemäß den Vorgaben der IsyFact mit der Fähigkeit zur Kommunikation mit anderen IT-Systemen ausstatten müssen und beschreibt, was bei der Umsetzung zu bedenken ist.

Dazu beschreibt das Kapitel <<maven-konfiguration>> zunächst die grundlegende Konfiguration, um den Baustein in ein IT-System einzubinden.
Danach beschreibt das Dokument die Realisierung eines Services in den Kapiteln:

* <<realisierung-remote-bean>>,
* <<realisierung-exception-fassade>>,
* <<realisierung-service-fassade>>,
* <<realisierung-to>>.

Danach geht es um die <<paketierung>> und die <<nutzung>> durch ein anderes IT-System.
// end::inhalt[]