[bibliography]
== Literaturverweise

////
// Referenzen dürfen nur aus Buchstaben und Zahlen bestehen. Es sind keine Sonderzeichen erlaubt:
// erlaubt: IsyFactEinstieg
// nicht erlaubt: IsyFact-Einstieg
// Referenzen werden in den folgenden Dokumenten gefunden und zu Literaturverzeichnissen verarbeitet:
// docinfo.adoc, thisdoc.adoc, inhalt.adoc, anhaenge.adoc
// Zwischen den einzelnen Einträgen dürfen nur Zeilenumbrüche ohne Leerzeichen stehen.
////

////
// Referenzen auf IsyFact
////

- [[[IsyFactEinstieg]]] +
  IsyFact-Einstieg +
  00_Allgemein\IsyFact-Einstieg.pdf

- [[[IsyFactGlossar]]] +
  IsyFact Glossar +
  00_Allgemein\IsyFact-Glossar.pdf

- [[[IsyFactNamenskonventionen]]] +
  IsyFact – Namenskonventionen +
  00_Allgemein\IsyFact-Namenskonventionen.pdf

- [[[IsyFactReferenzarchitektur]]] +
  IsyFact – Referenzarchitektur +
  00_Allgemein\IsyFact-Referenzarchitektur.pdf

- [[[IsyFactReferenzarchitekturITSystem]]] +
  IsyFact – Referenzarchitektur für IT-Systeme +
  00_Allgemein\IsyFact_Referenzarchitektur-IT-System.pdf

- [[[TailoringVorlage]]] +
  Vorlage für IsyFact Tailoring Dokument +
  00_Allgemein\IsyFact-Tailoring.dotx

- [[[IsyFactTutorial]]] +
  IsyFact–Tutorial +
  00_Allgemein\IsyFact-Tutorial.pdf

- [[[IsyFactVersionierung]]] +
  IsyFact-Versionierung +
  00_Allgemein/IsyFact-Versionierung.pdf

- [[[ProduktKatalog]]] +
  IsyFact Produktkatalog +
  00_Allgemein\Produktkatalog_IsyFact.xlsx

- [[[Aenderungshistorie]]] +
  IsyFact Änderungshistorie +
  00_Allgemein\Aenderungshistorie.xlsx

- [[[DetailkonzeptKomponenteAnwendungskern]]] +
  Detailkonzept der Komponente Anwendungskern +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Anwendungskern.pdf

- [[[DetailkonzeptKomponenteBatch]]] +
  Detailkonzept Komponente Batch +
  10_Blaupausen/technische_Architektur/Detailkonzept_Komponente_Batch.pdf

- [[[DetailkonzeptKomponenteDatenzugriff]]] +
  Detailkonzept Komponente Datenzugriff +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Datenzugriff.pdf

- [[[DetailkonzeptKomponenteService]]] +
  Detailkonzept Komponente Service +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Service.pdf

- [[[DetailkonzeptKomponenteWebGUI]]] +
  Detailkonzept Komponente Web-GUI +
  10_Blaupausen/technische_Architektur/Detailkonzept_Komponente_Web_GUI.pdf

- [[[GrundlagenInterneServicekommunikation]]] +
  Grundlagen der Servicekommunikation innerhalb der Plattform +
  10_Blaupausen\Integrationsplattform\Grundlagen_interne_Servicekommunikation.pdf

- [[[KonzeptDatumZeit]]] +
  Konzept Datum & Zeit +
  20_Bausteine\Datum_Zeit\Konzept_Datum_Zeit.pdf

- [[[NutzungsvorgabenDatumZeit]]] +
  Nutzungsvorgaben Datum & Zeit +
  20_Bausteine\Datum_Zeit\Nutzungsvorgaben_Datum_Zeit.pdf

- [[[KonzeptFehlerbehandlung]]] +
  Konzept Fehlerbehandlung +
  20_Bausteine\Fehlerbehandlung\Konzept_Fehlerbehandlung.pdf

- [[[NutzungsvorgabenSpringLDAP]]] +
  Nutzungskonzept Spring-LDAP +
  20_Bausteine\LDAP-Zugriffe\Nutzungsvorgaben_Spring_LDAP.pdf

- [[[KonzeptLogging]]] +
  Konzept Logging +
  20_Bausteine\Logging\Konzept_Logging.pdf

- [[[NutzungsvorgabenLogging]]] +
  Nutzungsvorgaben Logging +
  20_Bausteine\Logging\Nutzungsvorgaben_Logging.pdf

- [[[NutzungsvorgabenPolling]]] +
  Konzept Protokollierung +
  20_Bausteine\Polling\Nutzungsvorgaben_Polling.pdf

- [[[NutzungsvorgabenSicherheit]]] +
  Nutzerdokumentation Sicherheit +
  20_Bausteine\Sicherheitskomponente\Nutzungsvorgaben_Sicherheit.pdf

- [[[KonzeptUmgangMitSonderzeichen]]] +
  Transkriptions-Regeln +
  20_Bausteine\Sonderzeichen\Konzept_Umgang_mit_Sonderzeichen.pdf

- [[[SLMapping]]] +
  Mapping-Tabelle für die Transformation von String.Latin-Zeichen +
  20_Bausteine\Sonderzeichen\Mappingtabelle.xls

- [[[Transskriptionsregeln]]] +
  Transkriptions-Regeln +
  20_Bausteine\Sonderzeichen\Transkriptionsregeln.xls

- [[[KonzeptTaskScheduling]]] +
  Konzept Task Scheduling +
  20_Bausteine\Task_Scheduling\Konzept_Task_Scheduling.pdf

- [[[NutzungsvorgabenTaskScheduling]]] +
  Nutzungsvorgaben Task Scheduling +
  20_Bausteine\Task_Scheduling\Nutzungsvorgaben_Task_Scheduling.pdf

- [[[KonzeptUeberwachungKonfiguration]]] +
  Konzept Überwachung und Konfiguration +
  20_Bausteine\Ueberwachung_Konfiguration\Konzept_Ueberwachung_Konfiguration.pdf

- [[[NutzungsvorgabenIsyUtil]]] +
  Nutzungskonzept Isy-Util +
  20_Bausteine\Util\Nutzungsvorgaben_Isy_Util.pdf

- [[[AnleitungDatenflussdiagramme]]] +
  Anleitung zur Erstellung und zum Lesen von Datenflussdiagrammen +
  40_Methodik\10_Systemspezifikation\Anleitung_zu_Datenflussdiagrammen.dotx

- [[[IsyFactVorlageAnforderungsliste]]] +
  Vorlage für Anforderungsliste +
  40_Methodik\10_Systemspezifikation\IsyFact-Vorlage-Anforderungsliste.xlsx

- [[[IsyFactSystementwurf]]] +
  Vorlage für Systementwürfe +
  40_Methodik\20_Systementwurf\IsyFact-Vorlage_Systementwurf.dot

- [[[IsyFactSystemspezifikation]]] +
  Vorlage für Systemspezifikationen +
  40_Methodik\20_Systementwurf\IsyFact-Vorlage_Systemspezifikation.dot

- [[[IsyFactVorlageSystemhandbuch]]] +
  Vorlage Systemhandbuch +
  40_Methodik\30_Implementierung\IsyFact-Vorlage_Systemhandbuch.dotx

- [[[JavaProgrammierkonventionen]]] +
  Java-Programmierkonventionen +
  40_Methodik\30_Implementierung\Java-Programmierkonventionen.pdf

- [[[EinrichtungEntwicklungsumgebung]]] +
  Einrichtung einer Entwicklungsumgebung – Boilerplate Code und Formatierung +
  50_Werkzeuge/Einrichtung_Entwicklungsumgebung.pdf

- [[[HandbuchFuerTechnischeAutoren]]] +
  Handbuch für technische Autoren +
  50_Werkzeuge/Handbuch_fuer_technische_Autoren.pdf

- [[[LeitfadenEntwicklungsumgebung]]] +
  Leitfaden zur Einrichtung der Entwicklungsumgebung +
  50_Werkzeuge/Leitfaden-Entwicklungsumgebung.pdf

- [[[NutzungsvorgabenBenutzerverwaltung]]] +
  Nutzungsvorgaben Benutzerverwaltung +
  20_Bausteine/Benutzerverwaltung/Nutzungsvorgaben_Benutzerverwaltung.pdf

- [[[Vorlageanwendung]]] +
  IsyFact-Vorlageanwendung "Terminfindung" +
  https://github.com/IsyFact/IsyFact-Vorlageanwendung

////
// Weblinks & Verweise auf Bücher
////

- [[[Ambler1999]]] +
  Writing Robust Java Code. The AmbySoft Inc. Coding Standards for Java v17.01d +
  http://www.ambysoft.com/downloads/javaCodingStandards.pdf

- [[[BaKi07]]] +
  Christian Bauer, Gavin King. Java Persistence with Hibernate. 2007. Manning Publications

- [[[Batch]]] +
  Batch-Verarbeitung mit Hibernate +
  http://www.hibernate.org/hib_docs/v3/reference/en/html/batch.html (Zugriff am 10.12.2014)

- [[[ITGrundschutzM471]]] +
  M 4.71 Restriktive Handhabung von Datenbank-Links +
  https://www.bsi.bund.de/DE/Themen/ITGrundschutz/ITGrundschutzKataloge/Inhalt/_content/m/m04/m04071.html +
  (Zugriff am 27.03.2018)

- [[[Bloch2008]]] +
  Joshua Bloch. Effective Java Second Edition. 2008. Addison Wesley.

- [[[Collections]]] +
  Hibernate Documentation: Chapter 6. Collection Mapping +
  http://www.hibernate.org/hib_docs/v3/reference/en/html/collections.html (Zugriff am 10.12.2014)

- [[[CommonEL]]] +
  Common Expression Language +
  http://commons.apache.org/el/

- [[[Deme05]]] +
  Zeitmaschine – Temporale Datenhaltung +
  http://www.sigs-datacom.de/fileadmin/user_upload/zeitschriften/js/2003/05/demelt_JS_05_03.pdf

- [[[DGSG]]] +
  Oracle: Globalization Support Guide 10g Release 2 (10.2) +
  http://download.oracle.com/docs/cd/B19306_01/server.102/b14225.pdf

- [[[Facelets]]] +
  Facelets +
  https://facelets.dev.java.net/

- [[[ITGS06]]] +
  IT-Grundschutzkatalog, Baustein B 1.12, Stand 2006 +
  https://www.bsi.bund.de/DE/Themen/ITGrundschutz/itgrundschutz_node.html

- [[[jenerate]]] +
  jenerate - Java Generation Plugin for Eclipse +
  https://github.com/maximeAudrain/jenerate

- [[[JMXBestPrac]]] +
  Java Management Extensions (JMX) - Best Practices +
  http://java.sun.com/javase/technologies/core/mntr-mgmt/javamanagement/best-practices.jsp

- [[[JMXParam]]] +
  Monitoring and Management Using JMX +
  http://java.sun.com/j2se/1.5.0/docs/guide/management/agent.html

- [[[JPA]]] +
  Java Persistence API +
  http://java.sun.com/javaee/overview/faq/persistence.jsp

- [[[OWASP10]]] +
  OWASP Top 10 Project +
  https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project

- [[[SAGA40]]] +
  SAGA Version 4.0 – Standards und Architekturen für E-Government-Anwendungen; Publikation der KBSt; +
  http://www.kbst.bund.de/saga

- [[[SemanticVersioning]]] +
  Semantic Versioning 2.0.0 +
  http://semver.org/spec/v2.0.0.html [Zugriff am 05.03.2018]

- [[[Spring]]] +
  Spring Framework Reference Documentation +
  http://docs.spring.io/spring-framework/docs/5.1.x/spring-framework-reference/

- [[[SpringLDAP]]] +
  Spring LDAP +
  http://www.springframework.org/ldap (Zugriff am 10.12.2014)

- [[[SUNRI]]] +
  SUN Referenzimplementierung JSF +
  http://java.sun.com/javaee/javaserverfaces/

- [[[Sun1997]]] +
  Java Code Conventions. +
  http://java.sun.com/docs/codeconv/

- [[[SWF]]] +
  Spring Web Flow Dokumentation +
  http://static.springsource.org/spring-webflow/docs/2.4.x/reference/html/

- [[[Tomahawk]]] +
  Apache JSF Komponentenbibliothek +
  http://myfaces.apache.org/tomahawk/index.html

- [[[Ucp15]]] +
  Universal Connection Pool for JDBC Developer's Guide +
  https://docs.oracle.com/cd/E11882_01/java.112/e12265/optimize.htm (Zugriff am 13.08.2015)

- [[[Vermeulen2000]]] +
  Allan Vermeulen, Scott W. Ambler, Greg Baumgardner, Eldon Metz, Trevor Misfeldt, Jim Shur, Patrick Thomson. The Elements of Java Style. 2000. Cambridge University

- [[[WikiJSF]]] +
  JavaServer Faces +
  http://de.wikipedia.org/wiki/JavaServer_Faces

- [[[XOEVStringLatin]]] +
  Handbuch zur Entwicklung XÖV-konformer IT-Standards (Anhang A) +
  http://www.xoev.de/sixcms/media.php/13/2010-03-02-Handbuch-final.pdf (Zugriff am 11.12.2014)

////
// Externe Referenzen
////

- [[[Berechtigungskonzept]]] +
  Berechtigungskonzept +
  Muss projektspezifisch erstellt werden

- [[[DeploymentKonzept]]] +
  Konzept Deployment für IsyFact-Anwendungen +
  30_Plattform\Konzept_Deployment.pdf

- [[[IsyFactJQuery]]] +
  Paketierte JQuery-Dateien für IsyFact-Anwendungen +
  60_Software\Bibliotheken\web-gui

- [[[KonzeptLoggingInfrastrukturELK]]] +
  Konzept Logging Infrastruktur ELK +
  30_Plattform\Konzept_Logging-Infrastruktur_ELK.pdf

- [[[NutzungskonzeptHTTPServer]]] +
  Nutzungskonzept HTTP Server +
  30_Plattform/Nutzungskonzept_Apache_HTTP_Server.pdf

- [[[NutzungsvorgabenLogserver]]] +
  Nutzungsvorgaben Logserver +
  Link wird ergänzt, wenn Dokument fertiggestellt wurde

- [[[ProtokollierungKonzept]]] +
  Konzept Protokollierung +
  20_Bausteine\Protokollierung_Protokollrecherche\Konzept_Protokollierung.pdf

- [[[RegelwerkKonzept]]] +
  Konzept Regelwerk +
  20_Bausteine\Regelwerk\Konzept_Regelwerk.pdf

- [[[ServiceGatewaySystementwurf]]] +
  Systemdokumentation Service-Gateway +
  20_Bausteine/Service-Gateway/Systemdokumentation_Service-Gateway.pdf

- [[[Styleguide]]] +
  Styleguide +
  20_Bausteine\Styleguide\Styleguide.pdf

- [[[SystemdokumentationServiceGateway]]] +
  Systemdokumentation Service-Gateway +
  20_Bausteine/Service-Gateway/Systemdokumentation_Service-Gateway.pdf

- [[[TomcatNutzungskonzept]]] +
  Nutzungskonzept Apache Tomcat +
  30_Plattform\Nutzungskonzept_Apache_Tomcat_8.pdf