= Konzept Sicherheit: Einleitung
include::../../../common/isyfact-attributes.adoc[]
include::../../../common/attributes.adoc[]

// tag::inhalt[]
[[einleitung]]
== Einleitung

Sicherheit ist ein zentrales Thema einer jeden Fachanwendung.
Bei der Umsetzung von Fachanwendungen in IT-Systeme werden ein Gutteil der Anforderungen an die Sicherheit durch Maßnahmen der IT-Sicherheit abgedeckt.
Die IsyFact richtet sich beim Thema Sicherheit nach behördlichen Standards sowie De-Facto-Standards aus der Industrie:

* <<ITGrundschutz>>
* <<OWASP10>>

Dieses Dokument konzentriert sich auf die konzeptionellen Aspekte der Authentifizierung und Autorisierung.
Es sorgt dafür, dass Authentifizierung und Autorisierung in allen IT-Systemen gleichartig umgesetzt wird und grundlegende Anforderungen an die IT-Sicherheit eingehalten werden.
Es richtet sich vor allem an Software-Architekten, die eine Fachanwendung gemäß den Vorgaben der IsyFact absichern müssen und beschreibt, wie und in welchen Teilen eines IT-Systems die Authentifizierung und Autorisierung umzusetzen ist.

// TODO Nach Bearbeitung des Dokuments noch einmal nachziehen!
Dazu wird zunächst in einem Überblick erläutert, wie die Sicherheitsarchitektur auf Ebene der Systemlandschaft und auf Ebene eines einzelnen IT-Systems aussieht.

Im Abschnitt <<rollen-und-rechte>> wird erläutert, wie für eine neue Fachanwendung das Rollenmodell definiert, in das Benutzerverzeichnis eingespielt und für eine Fachanwendung konfiguriert wird.

Im Abschnitt <<autorisierung-innerhalb-einer-anwendung>> wird auf die Umsetzung der Autorisierung in denen der Fachanwendung entsprechenden IT-Systemen eingegangen.
Dieser Abschnitt erläutert die Verwendung des Bausteins Sicherheit innerhalb einer Anwendung.

Im Abschnitt <<weitere-konzepte>> werden weitere Vorgaben zur Verwendung der Komponente Sicherheit gemacht.
Hier wird der Aufruf von Nachbarsystemen, Behandlung der Korrelations-ID und der Test von Anwendungen erläutert.

// end::inhalt[]