= Konzept HTTP Invoker: Einleitung
include::{isy-dokumentvorlagen}/docs/common/isyfact-attributes.adoc[]

// tag::inhalt[]
[[einleitung]]
== Einleitung

[NOTE]
====
Dieses Dokument ist aus mehreren Quellen entstanden und fasst die vorhandene Dokumentation zum Thema HTTP Invoker zusammen.
Der Baustein HTTP Invoker steht unter Bestandsschutz und wird nicht mehr aktiv weiterentwickelt.
Er wird in einem der nächsten Major Releases aus der IsyFact entfernt.
// TODO Links zum REST-Konzept einfügen.
====

Spring HTTP Invoker ist ein leichtgewichtiges Protokoll, das transparente Service-Aufrufe zwischen Java-Anwendungen ermöglicht.
Es verwendet hauptsächlich die Standardmechanismen von Java zur Serialisierung und stellt Services über HTTP bereit.

Dieses Dokument konzentriert sich auf die konzeptionellen Aspekte der Verwendung von HTTP Invoker.
Es sorgt dafür, dass Services in allen IT-Systemen gleichartig umgesetzt werden und grundlegende Anforderungen an die Erstellung und Nutzung von Services eingehalten werden.

Das Dokument richtet sich vor allem an Software-Architekten und beschreibt, wie ein IT-System mit einer Service-Schnittstelle basierend auf HTTP Invoker versehen wird, oder solche Schnittstellen aufruft.
Dabei vertieft es die Grundlagen, die im <<DetailkonzeptKomponenteService>> beschrieben werden und wendet sie auf das Service-Framework HTTP Invoker an.

Das Dokument erläutert im Kapitel <<kommunikation-mit-http-invoker>> zunächst die Grundlagen, Rahmenbedingungen und Beschränkungen des Einsatzes von HTTP Invoker.
Danach beleuchtet das Kapitel <<aufbau-der-service-logik>>, wie die Komponente Service architektonisch mit HTTP Invoker aufgebaut ist.
Im Kapitel <<auslieferung-einer-service-schnittstelle>> geht es darum, wie HTTP Invoker Schnittstellen ausgeliefert werden und was dabei zu beachten ist.
Schließlich zeigt das Dokument noch Vorgaben zu den Themen <<versionierung>> und <<namenskonventionen>> auf.
// end::inhalt[]