[[aufbau-von-isy-util]]
= Aufbau von isy-util

[[common]]
== Common

Das Package `de.bund.bva.isyfact.util.common` enthält allgemeine Klassen, die keiner speziellen Funktionalität zugeordnet sind.
Zurzeit besteht sie aus folgender Klasse:

* `RecursiveToStringBuilder`: Diese Klasse erzeugt eine Textausgabe für Objekte, die keine geeignete `toString`-Methode implementieren.

[[package-exception]]
== Package exception

In `de.bund.bva.isyfact.util.exception` sind Klassen enthalten, die für die Fehlerbehandlung einzusetzen sind:

* `MessageSourceFehlertextProvider`: Durch diese Klasse wird der `FehlertextProvider` implementiert, der sich im Package `de.bund.bva.isyfact.exception` der <<glossar-Bibliothek>> isy-exception-core befindet.
Der `FehlertextProvider` beschreibt Methoden zum Auslesen von Fehlertexten auf Basis von IDs der Ausnahmen und Parameter, sofern welche vorhanden sind.

[[package-spring]]
== Package spring

Das Package `de.bund.bva.isyfact.util.spring` enthält Werkzeuge für den Umgang mit Spring:

* `MessageSourceHolder`: Der `MessageSourceHolder` ist eine Referenz auf die aktuelle `MessageSource`-Bean.
Zusätzlich bietet er Convenience-Funktionen zum Auslesen von `ResourceBundle`-Einträgen aus der `MessageSource`.

// tag::architekturregel[]
[ARCHITEKTURREGEL]
====
Der Block ARCHITEKTURREGEL beschreibt Regeln, welche die IsyFact an die Architektur von mit ihr entwickelten IT-Systemen stellt.
Die Regeln zielen somit vor allem auf eine korrekte Umsetzung der Referenzarchitektur ab und sind fast ausschließlich technischer Natur.
Sie bilden die Grundlage für eine einheitliche softwaretechnische Architektur der IT-Systeme.
====
// end::architekturregel[]

// tag::sicherheit[]
[SICHERHEIT]
====
Der Block SICHERHEIT beschreibt Regeln, welche die IsyFact an die IT-Sicherheit von mit ihr entwickelten IT-Systemen stellt.
Die Regeln stellen vor allem eine, vom festgestellten Schutzbedarf abhängige, sichere Umsetzung der IT-Systeme sicher.
====
// end::sicherheit[]
