[[einleitung]]
= Einleitung

Die IsyFact sieht die Nutzung eines zentralen Session-Speichers vor, um Sessions von Webanwendungen zu 
persistieren und diese damit allen redundanten Instanzen einer Anwendung verfügbar zu machen.
Dies wird im <<KonzeptSessionManagement>> erläutert.

Die vorliegenden Nutzungvogaben beschreibt den Aufbau eines Redis-Clusters als zentraler Session-Speicher.
Es richtet sich an alle, die am Aufbau und Betrieb des Clusters beteiligt sind.

[[aufbau-und-zweck-des-dokuments]]
== Aufbau und Zweck des Dokuments

Die Nutzungsvorgaben sind wie folgt aufgebaut:

* Kapitel <<cluster-infrastruktur>>: Zeigt den Zielzustand der Cluster-Infrastruktur.
* Kapitel <<installation-und-konfiguration>>: Beschreibt die Installation und Konfiguration des Clusters
* Kapitel <<betriebsszenarien>>: Beschreibt Szenarien bei Betrieb des Clusters
* Kapitel <<ueberwachung>>: Beschreibt, wie der Cluster überwacht wird (Monitoring)
* Kapitel <<themensammlung>>: Beinhaltet eine Sammlung von wichtigen Aspekte des Betriebs von Redis

Die Beschreibungen aus diesen Kapiteln über Installation, Betrieb und Überwachung sind bei Einrichtung des Clusters 
in ein umgebungsspezifisches Betriebshandbuch zu überführen.
