[[AppendixA]]
= Anhang A

[[konfiguration]]
== Konfiguration

[[vollstaendige-liste-der-konfigurationsparameter]]
=== Vollständige Liste der Konfigurationsparameter

Im Folgenden werden sämtliche Konfigurationsparameter von isy-sesion aufgelistet.

:desc-table-Confip: Konfigurationsparameter
[id="table-Confip",reftext="{table-caption} {counter:tables}"]	
.{desc-table-Confip}
[cols="6,4m,2m,3",options="header"]
|====
|Parameter |Wertebereich |Default |Beschreibung
4+|*Pflichtparameter*
m|filter.session.locking |Boolean |_keiner_ |Aktiviert den Locking-Mechanismus des IsySessionRepositoryFilters.
m|filter.session.logging |Boolean |_keiner_ |Aktiviert das Loggen durch den SessionLoggingFilters. Muss nur gesetzt werden, wenn der SessionLoggingFilter eingesetzt wird.
4+|*Optionale Parameter*
m|session.redis.active |Boolean |true |Session-Persistierung in Redis aktivieren / deaktivieren.
m|filter.session.locking.verbs |String

Beispiel: GET,POST |_keiner_ |Komma seperierte Liste von HTTP-Methoden bei denen ein Write Lock verwendet werden soll.
m|filter.session.locking.uri[0..n]

Bspl:
filter.session.locking.uri[0] = http://black.listed.uri |String |_keiner_ |Aktiviert ein Writelock, eine Anfrage auf eine der angebenen URIs eingeht.
|====

[[vollstaendiges-konfigurationstemplate]]
=== Vollständiges Konfigurationstemplate

:desc-listing-konfigurationstemplate: Vollständiges Konfigurationstemplate
[id="listing-konfigurationstemplate",reftext="{listing-caption} {counter:listings }"]
.{desc-listing-konfigurationstemplate}
[source,php]
----
# ---
# --- ALLGEMEINE KONFIGURATIONSPARAMETER
# ---
# Aktivieren der Sessionverwaltung.
# Wertebereich: Boolean.Default: true.
session.redis.active=true

# Aktiviert den Locking-Mechanismus vom IsySessionRepositoryFilter
# Wertebreich: Boolean
filter.session.locking = true

# Aktiviert Write-Locks für Anfragen mit folgenden HTTP-Methoden
# Wertebereich: String
filter.session.locking.verbs = post,get

# Aktiviert Write-Locks für Anfragen mit folgenden URIs
# Wertebereich: String
filter.session.locking.uri[0] = http://black.listed.uri0
filter.session.locking.uri[1] = http://black.listed.uri1
filter.session.locking.uri[2] = http://black.listed.uri2

# Aktiviert das Loggen der Session durch den SessionLoggingFilter
# Wertebreich: Boolean
filter.session.logging = false
----

[[liste-der-redissonparameter]]
=== Liste der Redissonparameter

Hier sind die relevanten Konfigurationsparameter für den Redisson Client gelistet.
Eine vollständige Liste aller Parameter lässt sich auf https://github.com/redisson/redisson/wiki/2.-Configuration einsehen.

:desc-table-Confip: Redisson Konfigurationsparameter
[id="table-redissonyaml",reftext="{table-caption} {counter:tables}"]
.{desc-table-redissonyaml}
[cols="6,4m,2m,3",options="header"]
|====
|Parameter |Wertebereich |Default |Beschreibung
4+|*_clusterServersConfig_*
4+|*Pflichtparameter*
m|$$nodeAddresses$$
|$$- "redis://<IP>:<Port>"$$

$$Bspw.$$
$$- "redis://127.0.0.1:7004"$$
|_keiner_
|Adressen der Redis-Knoten.

Nutze das $$rediss://$$ Protokoll für eine SSL Verbindung.
4+|*Optionale Parameter*
m|scanInterval |Long |1000 |Redis Cluster Scaninterval in Millisekunden.
m|readMode |SLAVE, MASTER, MASTER_SLAVE |SLAVE |Setze Knotentyp für Leseoperationen

SLAVE - Lese von Slave Knoten. Nutzt MASTER, wenn keine SLAVES vorhanden sind.
MASTER - Lese von dem Master Knoten.
MASTER_SLAVE - Lese von Master und Slave Knoten.
m|subscriptionMode |org.redisson.connection.balancer.WeightedRoundRobinBalancer,
org.redisson.connection.balancer.RoundRobinLoadBalancer,
org.redisson.connection.balancer.RandomLoadBalancer |org.redisson.connection.balancer.RoundRobinLoadBalancer | Verbindungs Load Balancer für mehrere Redis Server.
m|subscriptionConnectionMinimumIdleSize |Integer |1 |Minimale Pool Größe für inaktive Verbindungen für (pub/sub) Kanäle. Genutzt von RTopic, RPatternTopic, RLock, RSemaphore, RCountDownLatch, RClusteredLocalCachedMap, RClusteredLocalCachedMapCache, RLocalCachedMap, RLocalCachedMapCache Objekte und Hibernate READ_WRITE Cache Strategie.
m|subscriptionConnectionPoolSize |Integer |50 |Maximale Pool Größe für inaktive Verbindungen für (pub/sub) Kanäle. Genutzt von RTopic, RPatternTopic, RLock, RSemaphore, RCountDownLatch, RClusteredLocalCachedMap, RClusteredLocalCachedMapCache, RLocalCachedMap, RLocalCachedMapCache Objekte und Hibernate READ_WRITE Cache Strategie.
m|slaveConnectionMinimumIdleSize |Integer |24 |Minimale Anzahl inaktiver Redis 'slave' Knoten Verbindungen für *jeden* Slave Knoten.
m|slaveConnectionPoolSize |Integer |64 |Maximale Anzahl inaktiver Redis 'slave' Knoten Verbindungen für *jeden* Slave Knoten.
m|masterConnectionMinimumIdleSize |Integer |24 |Minimale Anzahl inaktiver Redis 'master' Knoten Verbindungen für *jeden* Slave Knoten.
m|masterConnectionPoolSize |Integer |24 |Maximale Anzahl inaktiver Redis 'master' Knoten.
m|idleConnectionTimeout |Long |10000 |Wenn eine inaktive Verbindung für eine bestimmte Zeit nicht verwendet wird, und die Anzahl inaktiver Verbindungen größer ist als die minimale Anzahl wird die Verbindung nach x Millisekunden geschlossen.
m|connectTimeout |Long |10000 |Timeout in Millisekunden wärend einer Verbindung einem Redis Server.
m|timeout |Long |3000 |Redis Antwort Timeout. Startet wenn eine Anfrage an den Redis geschickt wird.
m|retryAttempts |Integer |3 |Eine Fehler wird geworfen wenn *retryAttempts* oft keine erfolgreiche Anfrage ausgeschickt werden kann.
m|retryInterval |Long |1500 |Zeitinterval in Millisekunden in dem erneut versucht wird eine Anfrage an den Redis Server zu senden.
m|password |String |_null_ |Passwort für den Redis Server
m|username |String |_null_ |Nutzername für den Redis Server
m|subscriptionsPerConnection |Integer |5 |Unterzeichnung pro Limit der unterzeichneten Verbundungen. Genutzt von RTopic, RPatternTopic, RLock, RSemaphore, RCountDownLatch, RClusteredLocalCachedMap, RClusteredLocalCachedMapCache, RLocalCachedMap, RLocalCachedMapCache Objekte und Hibernate READ_WRITE Cache Strategie.
m|clientName |String |_null_ |Name des Clienten
m|pingConnectionInterval |Long |0 |Definiert das Zeitinterval in dem der Ping Befehl pro Verbindung zum Redis gesendet wird. `0` schaltet das Pingen ab.
m|keepAlive |Boolean |false |Aktiviert TCP-keepAlive für die Verbindung.
m|tcpNoDelay |Boolean |false |Aktiviert TCP-noDelay für die Verbindung.
4+|*_Allgemeine Konfigurationen_*
4+|*Optionale Parameter*
m|nettyThreads |Intger |32 |Anzahl Threads, die auf alle Redis Clienten von Redisson verteil werden. Netty Threads, die in der Verarbeitung von Antworten und Senden von Anfragen eingesetzt werden.
m|threads |Integer |16 |Anzahl Threads, die auf die Listener von RTopic Objekten, Invokation Handler von RRemoteService und RExecutorService Tasks verteilt werden.
m|codec |org.redisson.codec.FstCodec,
org.redisson.codec.JsonJacksonCodec,
org.redisson.codec.MarshallingCodec,
org.redisson.codec.AvroJacksonCodec,
org.redisson.codec.SmileJacksonCodec,
org.redisson.codec.CborJacksonCodec,
org.redisson.codec.MsgPackJacksonCodec,
org.redisson.codec.IonJacksonCodec,
org.redisson.codec.KryoCodec,
org.redisson.codec.SerializationCodec,
org.redisson.codec.LZ4Codec,
org.redisson.codec.SnappyCodec,
org.redisson.codec.SnappyCodec,V2
org.redisson.codec.TypedJsonJacksonCodec,
org.redisson.client.codec.StringCodec,
org.redisson.client.codec.LongCodec,
org.redisson.client.codec.ByteArrayCodec,
org.redisson.codec.CompositeCodec |org.redisson.codec.FstCodec |Redis Data Codec, der beim Lesen und Schreiben verwendet wird.
m|transportMode |TransportMode.NIO,
TransportMode.EPOLL,
TransportMode.KQUEUE |TransportMode.NIO |Transport Modus für den Client.
`TransportMode.EPOLL` braucht `netty-transport-native-epoll` auf dem Klassenpfad.
`TransportMode.KQUEUE` braucht `netty-transport-native-kqueue` auf dem Klassenpfad.
|====

[[migration-von-plis-tomcat]]
== Migration von plis-tomcat

Zur Migration von `plis-tomcat` auf `isy-session` sind die in Kapitel <<einbindung-und-konfiguration>>
beschriebenen Schritte analog durchzuführen.
Zusätzlich müssen folgende Bereinigungen vorgenommen werden.

.  **context.xml anpassen**: Den Session-Manager von `plis-tomcat` sowie das dazugehörende
Valve aus der `context.xml` des Tomcats entfernen.
Dies betrifft die folgenden Einträge
+
[source,xml]
----
<Manager className="de.bund.bva.pliscommon.tomcat.session.JdbcSessionManager" configuration="/opt/[Anwendung]/tomcat/conf/sessionmanager.properties" />

<Valve className="de.bund.bva.pliscommon.tomcat.session.JdbcSessionManagerValve" />
----
+
*Anmerkung:* Dies ist bereits ausreichend, um das Session-Management durch `plis-tomcat` zu deaktivieren.
.  **plis-tomcat-<x.x.x>.jar entfernen**. Die Datei befindet sich im Ordner `lib` des Tomcats.
.  **sessionmanager.properties löschen**: Die Datei befindet sich im Ordner `conf` des Tomcats
.  **TOMCAT_SESSIONS Tabelle löschen**: Die Tabelle muss mit folgenden Befehl im Schema der Anwendung gelöscht werden:

  DROP TABLE TOMCAT_SESSIONS

.  **DB-Skripte bereinigen**: Die Anlage der Tabelle `TOMCAT_SESSIONS` muss aus den Datenbankskripten
der Anwendung entfernt werden, so dass diese bei einer Neuinstallation nicht wieder angelegt wird.
.  *UCP aus Tomcat entfernen und in WAR-Datei aufnehmen:* Beim Einsatz von `plis-tomcat` wurde der Oracle
UCP im `lib`-Verzeichnis des Tomcats abgelegt.
Die WAR-Datei der Webanwendung beinhaltet den Oracle UCP hierbei nicht (Maven-Depency im Scope `provided`).
Mit `isy-session` benötigt der Tomcat selbst keine Datenbankverbindung mehr. Daher muss
..  der Oracle UCP aus dem `lib`-Verzeichnis des Tomcats entfernt und
..  die Angabe des Scopes der Maven-Dependency auf den UCP in der Webanwendung entfernt werden, so 
dass der UCP mit in die WAR-Datei aufgenommen wird.
